import { ROUTES } from "@/lib/routes";

export const CTA_REGISTRY = {
  HOME_EXPLORE: {
    id: "HOME_EXPLORE",
    label: "Explore Downtown",
    type: "route",
    href: ROUTES.explore,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  HOME_GET_CARD: {
    id: "HOME_GET_CARD",
    label: "Get Your Card",
    type: "route",
    href: ROUTES.residentAppCard,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  BECOME_PARTNER: {
    id: "BECOME_PARTNER",
    label: "Become a Partner",
    type: "route",
    href: ROUTES.partners,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  OPEN_MAP: {
    id: "OPEN_MAP",
    label: "Open the Map",
    type: "route",
    href: ROUTES.explore,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  GET_CARD: {
    id: "GET_CARD",
    label: "Get Your Card",
    type: "route",
    href: ROUTES.card,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  ASK_MAP: {
    id: "ASK_MAP",
    label: "Ask the Map",
    type: "state",
    href: null,
    apiAction: "/api/ask-map",
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: "We couldn't process that search right now.",
  },
  SAVE_ITEM: {
    id: "SAVE_ITEM",
    label: "Save",
    type: "api",
    href: null,
    apiAction: "/api/save",
    modal: null,
    disabledReason: null,
    successMessage: "Saved.",
    errorMessage: "That item could not be saved.",
  },
  RSVP_EVENT: {
    id: "RSVP_EVENT",
    label: "RSVP",
    type: "state",
    href: null,
    apiAction: null,
    modal: "event-rsvp",
    disabledReason: null,
    successMessage: "RSVP recorded.",
    errorMessage: "RSVP could not be completed.",
  },
  USE_PERK: {
    id: "USE_PERK",
    label: "Use Perk",
    type: "api",
    href: null,
    apiAction: "/api/redeem",
    modal: null,
    disabledReason: null,
    successMessage: "Perk redeemed.",
    errorMessage: "Perk redemption failed.",
  },
  SHOW_QR: {
    id: "SHOW_QR",
    label: "Show QR",
    type: "route",
    href: ROUTES.residentAppCard,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  START_PARTNER_PILOT: {
    id: "START_PARTNER_PILOT",
    label: "Start Partner Pilot",
    type: "route",
    href: ROUTES.partnerApply,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  OPEN_DASHBOARD: {
    id: "OPEN_DASHBOARD",
    label: "Open Dashboard",
    type: "route",
    href: ROUTES.partnerDashboard,
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
  CONTACT: {
    id: "CONTACT",
    label: "Contact",
    type: "route",
    href: "/#contact",
    apiAction: null,
    modal: null,
    disabledReason: null,
    successMessage: null,
    errorMessage: null,
  },
};

export function getCTA(id) {
  return CTA_REGISTRY[id] || null;
}

export function getCTAList(ids = []) {
  return ids.map((id) => getCTA(id)).filter(Boolean);
}
