import {
  BarChart3,
  Building2,
  Calendar,
  Hotel,
  Landmark,
  Megaphone,
  Route,
  Sparkles,
  Store,
  Users,
} from "lucide-react";

export const PARTNER_TYPE_ORDER = [
  "properties",
  "hospitality",
  "venues",
  "brands",
  "civic",
];

export const PARTNER_TYPE_CONTENT = {
  properties: {
    id: "properties",
    label: "Residential",
    shortLabel: "Residential",
    route: "/partners/residential",
    legacyRoutes: ["/partners/properties"],
    mapMode: "property",
    icon: Building2,
    eyebrow: "Residential Partner",
    heroTitle: "Activate your residents with local discovery",
    heroDescription:
      "Connect your building's residents to downtown venues, events, and exclusive perks. Drive engagement, retention, and neighborhood integration.",
    heroPrimaryCta: { label: "View system", href: "/partners/dashboard" },
    heroSecondaryCta: { label: "See examples", href: "/brands/four-seasons-residences" },
    heroStats: [
      { label: "Resident engagement", value: "73%" },
      { label: "Active properties", value: "28+" },
      { label: "Partner venues", value: "120+" },
    ],
    mapPreviewTitle: "Building + Resident Layer Preview",
    mapPreviewDescription: "What the resident layer looks like in practice.",
    mapPreviewChips: ["Resident layer", "Nearby perks", "Events", "Building-linked access"],
    secondaryStats: [
      { label: "Resident activation", value: "73%", detail: "+12% MoM" },
      { label: "Avg repeat usage", value: "52%", detail: "+8% MoM" },
      { label: "Venue partnerships", value: "12+", detail: "Growing" },
      { label: "Monthly scans", value: "2k+", detail: "+34% MoM" },
    ],
    modulesTitle: "How it works for residents",
    modules: [
      {
        title: "Resident Activation",
        metric: "73% Avg engagement",
        body: "Residents discover venues, events, and perks directly from your building app or onboarding.",
      },
      {
        title: "Venue Partnerships",
        metric: "12+ Partner venues",
        body: "Negotiate exclusive perks for residents at nearby restaurants, fitness, wellness.",
      },
      {
        title: "QR Entry Integration",
        metric: "2k+ Scans per week",
        body: "Residents tap a QR code to unlock their resident status and perks at each venue.",
      },
    ],
    stepsTitle: "How it works",
    stepsIntro: "Your building appears on the map with a resident layer. Residents can tap to view exclusive perks at nearby venues and save favorites.",
    workflow: [
      "Building setup — Configure your property and resident details.",
      "Map placement — Your building appears with resident layer on the map.",
      "Resident access — Residents get exclusive perks at partner venues.",
      "Live dashboard — Track engagement and venue partnerships in real time.",
      "Negotiation — We help arrange new venue partnerships.",
    ],
    useCasesTitle: "Use cases",
    useCases: [
      { title: "Resident onboarding", detail: "New residents explore neighborhoods on day one and discover 12+ exclusive perks immediately.", meta: "73% engagement" },
      { title: "Retention & community", detail: "Residents stay engaged with weekly venue partnerships, events, and exclusive offers.", meta: "52% repeat usage" },
      { title: "Venue partnerships", detail: "Negotiate exclusive resident perks at nearby restaurants, fitness, and wellness venues.", meta: "120+ venues" },
      { title: "Event activation", detail: "Promote resident-exclusive events and experiences across your community.", meta: "28+ active perks" },
    ],
    liveActivityTitle: "Live activity",
    liveActivity: [
      { title: "Resident scanned perk at Banger's", meta: "Venue QR", stamp: "2 min ago" },
      { title: "New venue partnership: Equinox", meta: "Admin", stamp: "15 min ago" },
      { title: "Resident saved event at Rainey St", meta: "Map", stamp: "34 min ago" },
      { title: "Redemption: 20% off at The Paseo", meta: "Venue", stamp: "1 hr ago" },
      { title: "New building onboarded: Four Seasons Residences", meta: "Admin", stamp: "3 hrs ago" },
      { title: "Resident engagement: +180% this month", meta: "Analytics", stamp: "4 hrs ago" },
    ],
    form: {
      title: "Ready to launch?",
      intro: "Tell us about your residential property and we'll help you get up and running.",
      roleOptions: ["Property", "Hotel", "Venue", "Brand", "Civic"],
      fields: ["Organization / Property name"],
      notes: "We'll be in touch within 24 hours to discuss your next steps.",
      prompts: [],
      submitLabel: "Get started",
    },
    faqTitle: "Residential FAQs",
    faqIntro: "Residential is how buildings connect residents to the downtown layer in a way that feels useful every day.",
    faqs: [
      { id: "res-1", question: "How does residential fit into Downtown Perks?", answer: "Residential turns where someone lives into a stronger entry point into downtown. Buildings become part of the same live map system residents use to decide where to go." },
      { id: "res-2", question: "What does a building actually offer through this?", answer: "Buildings offer neighborhood utility: nearby venues, events, perks, onboarding support, and a resident layer that feels like a real amenity instead of a static list." },
      { id: "res-3", question: "Why is this better than a static amenity list?", answer: "Because the value stays live. Places, events, and perks change with time, location, and resident intent, so the system keeps feeling useful after move-in." },
      { id: "res-4", question: "How do residents get in?", answer: "Residents open the system through a building-linked QR or app touchpoint, browse immediately, and unlock higher-intent actions like saving, RSVP, and card issuance when needed." },
      { id: "res-5", question: "What can a property measure?", answer: "Properties can measure scans, activations, repeat usage, perk unlocks, building-driven discovery, and which nearby places actually matter to residents." },
      { id: "res-6", question: "How does Downtown Perks work with BuildingLink?", answer: "It layers on top of existing resident workflows by giving buildings a live neighborhood experience and measurable local utility instead of replacing the building system." },
      { id: "res-7", question: "What is different between Downtown Perks and BuildingLink?", answer: "BuildingLink manages the property. Downtown Perks connects the property to the neighborhood around it and turns that into a live resident product." },
    ],
    closing: {
      title: "Ready to activate your residents?",
      description: "Let's connect your building to the Downtown Perks ecosystem.",
      primary: { label: "Get started", href: "/partners/dashboard" },
      secondary: { label: "View other partners", href: "/partners" },
    },
  },
  hospitality: {
    id: "hospitality",
    label: "Hospitality",
    shortLabel: "Hospitality",
    route: "/partners/hospitality",
    legacyRoutes: ["/partners/hotels"],
    mapMode: "hospitality",
    icon: Hotel,
    eyebrow: "Hotel Partner Layer",
    heroTitle: "Help guests find what to do from the moment they arrive.",
    heroDescription: "One QR code gives guests access to nearby dining, events, and local offers — without asking your front desk to handle it.",
    heroPrimaryCta: { label: "Connect your hotel", href: "/partner-workspace" },
    heroSecondaryCta: { label: "See the guest layer", href: "/partners/dashboard" },
    heroStats: [
      { label: "Hotels active", value: "9" },
      { label: "Guest interactions", value: "2,104" },
      { label: "Saves", value: "612" },
      { label: "RSVPs", value: "184" },
      { label: "Perk unlocks", value: "93" },
      { label: "Hubs trending", value: "4" },
    ],
    mapPreviewTitle: "Hotel Map",
    mapPreviewDescription: "What guests can reach from each location.",
    mapPreviewChips: ["Hotels 9", "Events nearby 8", "Guest favorites 6", "Walkable now 10", "Perks live 7", "Saved by guests 5"],
    liveMomentsTitle: "Guest flow in action",
    liveMoments: [
      { title: "Guest opened dinner near Rainey", meta: "Hotel Van Zandt", stamp: "Just now" },
      { title: "Guest saved sunset event nearby", meta: "Fairmont Austin", stamp: "3 min ago" },
      { title: "Guest unlocked welcome drink perk", meta: "Austin Proper", stamp: "Trending" },
      { title: "Guest opened coffee near Congress", meta: "Thompson Austin", stamp: "Nearby" },
    ],
    venueListTitle: "Hotels",
    venueList: [
      { name: "Hotel Van Zandt", value: "214" },
      { name: "Fairmont Austin", value: "198" },
      { name: "JW Marriott", value: "184" },
      { name: "The Line", value: "172" },
    ],
    secondaryStats: [
      { label: "Hotel views", value: "7,208" },
      { label: "Guest taps", value: "1,044" },
      { label: "Saves", value: "312" },
      { label: "RSVPs", value: "184" },
      { label: "Offer unlocks", value: "93" },
      { label: "Hotels live", value: "9" },
      { label: "QR access points", value: "18" },
      { label: "Avg nearby opens per guest", value: "4.2" },
      { label: "Guests who return to the map", value: "29%" },
      { label: "Nearby venues linked", value: "16" },
      { label: "Self-serve discovery rate", value: "71%" },
    ],
    stepsTitle: "How it works",
    stepsIntro: "From check-in to neighborhood use in one step.",
    workflow: [
      "Register the hotel — Set up the property and configure guest access.",
      "Add the QR touchpoint — Guests open the map from the lobby, elevator, or room — no app required.",
      "Nearby context is ready — Dining, events, and offers surface automatically based on proximity.",
      "Guests decide and go — One tap to save, directions when needed, offer redeemed on arrival.",
      "See what got used — Track which nearby places and events drove the most guest activity.",
    ],
    stepMetrics: ["18 QR access points", "16 nearby venues linked", "184 RSVPs", "93 offer unlocks"],
    useCasesTitle: "Guest experience",
    useCasesIntro: "What a guest does from scan to visit.",
    useCases: [
      { title: "Scan QR", detail: "In lobby, elevator, or room" },
      { title: "Open map", detail: "Downtown Perks loads instantly" },
      { title: "Save something nearby", detail: "Event, place, or perk" },
      { title: "Walk there", detail: "Live directions and distance" },
      { title: "Unlock a local perk", detail: "Tap to redeem at the venue" },
    ],
    liveActivityTitle: "Live hotels",
    liveActivityIntro: "Activity across live hotels.",
    liveActivity: [
      { title: "Hotel Van Zandt", meta: "Guest interactions 214 · Saves 44 · Unlocks 18", stamp: "+16% this week · Rainey Live Music Crawl" },
      { title: "Fairmont Austin", meta: "Guest interactions 198 · Saves 39 · Unlocks 16", stamp: "+10% this week · Waterfront Sunset Series" },
      { title: "JW Marriott", meta: "Guest interactions 184 · Saves 34 · Unlocks 14", stamp: "+8% this week · Congress Dining" },
    ],
    form: {
      title: "Get started",
      intro: "Share a few details and we will help you set up guest access and connect nearby context.",
      roleOptions: ["Property", "Hotel", "Venue", "Brand", "Civic"],
      fields: ["Hotel Name", "Your Name & Role", "Phone", "What are you looking to set up", "Tell us about your hotel and what you want to offer guests."],
      prompts: [
        "We want a simple neighborhood guide guests can open from the lobby.",
        "Help us set up QR access.",
        "We want guests to find dining and events nearby without asking staff.",
        "Show us how offers work for guests.",
      ],
      submitLabel: "Connect your hotel",
      footer: "Questions? partners@downtownperks.com",
    },
    faqTitle: "Hospitality FAQs",
    faqIntro: "Hospitality is about giving guests a better way into downtown through the same shared map system.",
    faqs: [
      { id: "hot-1", question: "How does this work for hotels?", answer: "Hotels use Downtown Perks as a guest entry point into nearby places, events, local movement, and curated local value." },
      { id: "hot-2", question: "Is this meant to replace concierge recommendations?", answer: "No. It removes routine friction and lets staff point guests to a live neighborhood layer instead of repeating static recommendations." },
      { id: "hot-3", question: "What guest actions matter most?", answer: "Opens, saves, nearby directions, RSVP activity, and perk unlocks show whether the guest layer is creating real movement." },
      { id: "hot-4", question: "Can this support event-linked stays?", answer: "Yes. Hotels can surface event-led suggestions, tie guest entry to district activity, and measure what guests actually use around those moments." },
      { id: "hot-5", question: "Does this only work for perks?", answer: "No. Perks are one part of the system. Dining, events, nearby places, and useful local context are all part of the guest layer." },
      { id: "hot-6", question: "Can this work with the systems we already use?", answer: "Yes. The guest layer is designed to sit alongside existing hospitality workflows without forcing a replacement project." },
      { id: "hot-7", question: "How does Downtown Perks work with a POS?", answer: "POS integration matters at the redemption and measurement layer. The guest experience itself stays simple: scan, decide, go, and track what converted." },
    ],
    closing: {
      title: "Hotel partner layer",
      description: "Your guests already want to explore. Make it simple. Nine hotels are live. Setup takes less than a day and works from the first QR scan.",
      primary: { label: "Connect your hotel", href: "/partner-workspace" },
      secondary: { label: "See the map", href: "/partners/dashboard" },
      footer: "Questions? Reach the team at partners@downtownperks.com",
    },
  },
  venues: {
    id: "venues",
    label: "Venues",
    shortLabel: "Venues",
    route: "/partners/venues",
    mapMode: "venue",
    icon: Store,
    eyebrow: "Venue Partner Layer",
    heroTitle: "Be on the map when people nearby are deciding where to go.",
    heroDescription: "Your place shows up at the right moment — when someone close by is looking for food, a drink, a class, or somewhere to go.",
    heroPrimaryCta: { label: "Add your venue", href: "/partner-workspace" },
    heroSecondaryCta: { label: "See the live map", href: "/downtown-perks/explore" },
    heroStats: [
      { label: "Venues active", value: "24" },
      { label: "Map views", value: "3,182" },
      { label: "Saves", value: "712" },
      { label: "Visits", value: "289" },
      { label: "Redemptions", value: "96" },
      { label: "Trending nearby", value: "7" },
    ],
    mapPreviewTitle: "Venue Map",
    mapPreviewDescription: "Where your venue fits in the neighborhood search.",
    mapPreviewChips: ["Venues 24", "Live now 8", "Offers 10", "Walkable now 12", "Trending 7", "Saved nearby 6"],
    liveMomentsTitle: "Decision moments happening now",
    liveMoments: [
      { title: '"coffee near Seaholm"', meta: 'Merit Coffee · 0.2 mi · Free drip with a pastry', stamp: '' },
      { title: '"dinner near Rainey"', meta: "Aba and Banger's · 0.3–0.4 mi · Offers active", stamp: '' },
      { title: '"wellness near Congress"', meta: 'Equinox · 0.5 mi · First class free', stamp: '' },
      { title: '"where should I meet someone"', meta: 'Half Step · 0.3 mi · Happy Hour on now', stamp: '' },
    ],
    venueListTitle: "Venues",
    venueList: [
      { name: "Half Step", value: "124 views" },
      { name: "Banger's", value: "110 views" },
      { name: "Merit Coffee", value: "98 views" },
      { name: "Equinox", value: "88 views" },
    ],
    secondaryStats: [
      { label: "Venue views", value: "3,182" },
      { label: "Saves", value: "712" },
      { label: "Visits", value: "289" },
      { label: "Redemptions", value: "96" },
      { label: "Offer opens", value: "402" },
      { label: "Venues live", value: "24" },
      { label: "Active offers", value: "10" },
      { label: "Avg walk time", value: "6 min" },
      { label: "Nearby searches", value: "402" },
      { label: "Event-linked venues", value: "8" },
      { label: "Repeat saves", value: "22%" },
    ],
    stepsTitle: "How it works",
    stepsIntro: "From map to door.",
    workflow: [
      "List your venue — Add your category, location, and basic details.",
      "Set your offer and timing — Tell people what is available and when.",
      "Appear at the right moment — Show up when someone nearby searches your category.",
      "They save or walk in — One tap. Directions if needed. Offer redeemed on arrival.",
      "Track what worked — Views, saves, visits, and redemptions broken down by offer.",
    ],
    stepMetrics: ["10 active offers", "289 visits", "96 redemptions", "402 nearby searches"],
    useCasesTitle: "How people find places",
    useCasesIntro: "The moment between \"I want to go somewhere\" and walking in the door.",
    useCases: [
      { title: '"coffee near Seaholm"', detail: '→ Merit Coffee · 0.2 mi · Free drip with a pastry' },
      { title: '"dinner near Rainey"', detail: "→ Aba and Banger's · 0.3–0.4 mi · Offers active" },
      { title: '"wellness near Congress"', detail: '→ Equinox · 0.5 mi · First class free' },
      { title: '"where should I meet someone"', detail: '→ Half Step · 0.3 mi · Happy Hour on now' },
    ],
    liveActivityTitle: "Live venues",
    liveActivityIntro: "Activity across live venues.",
    liveActivity: [
      { title: "Half Step", meta: "Views 124 · Saves 42 · Visits 19 · Redemptions 7", stamp: "+18% this week · Happy Hour Nearby" },
      { title: "Banger's", meta: "Views 110 · Saves 36 · Visits 17 · Redemptions 5", stamp: "+11% this week · Dinner near Rainey" },
      { title: "Merit Coffee", meta: "Views 98 · Saves 28 · Visits 15 · Redemptions 4", stamp: "+9% this week · Coffee near Seaholm" },
    ],
    form: {
      title: "Get started",
      intro: "List your place, connect an offer, and start appearing when people nearby are looking for somewhere to go.",
      roleOptions: ["Property", "Hotel", "Venue", "Brand", "Civic"],
      fields: ["Venue Name", "Your Name & Role", "Phone", "What are you looking to do", "Tell us about your venue and what you want to offer."],
      prompts: [
        "We want to appear when people nearby are searching our category.",
        "Help us add an offer.",
        "Show us how the map placement works.",
        "We want to connect our venue to nearby events.",
      ],
      submitLabel: "Add your venue",
      footer: "Questions? partners@downtownperks.com",
    },
    faqTitle: "Venue FAQs",
    faqIntro: "Venue partners use Downtown Perks to show up when nearby intent is already forming.",
    faqs: [
      { id: "ven-1", question: "How do venues appear in the system?", answer: "Venues can appear through map pins, nearby results, perk placements, event-linked visibility, booking actions, and repeat local discovery paths." },
      { id: "ven-2", question: "What makes this different from a listing site?", answer: "It is driven by proximity, timing, and live intent rather than passive browsing. The system is trying to help someone decide now." },
      { id: "ven-3", question: "What kinds of actions can a venue drive?", answer: "Views, saves, visit intent, directions, RSVP behavior, and redemption are all part of the venue loop." },
      { id: "ven-4", question: "Does this work for both everyday and event-driven traffic?", answer: "Yes. Everyday categories and event-linked traffic both fit the same map and conversion model." },
      { id: "ven-5", question: "What proof matters most for venue partners?", answer: "Nearby searches, saves, visits, repeat behavior, and redemptions show whether map visibility is turning into actual foot traffic." },
      { id: "ven-6", question: "Does Downtown Perks replace inKind or our POS?", answer: "No. It creates demand and tracks behavior around the visit. Payment and POS layers can stay where they are." },
      { id: "ven-7", question: "How does Downtown Perks work with inKind?", answer: "inKind can stay part of the payment or offer stack, while Downtown Perks handles discovery, context, and attribution." },
      { id: "ven-8", question: "How does Downtown Perks work with a POS?", answer: "POS becomes relevant at redemption and closed-loop measurement. The resident-facing experience stays light and map-native." },
    ],
    closing: {
      title: "Venue partner layer",
      description: "Your best customers are already nearby. 24 venues are live. Your offer goes up in minutes and can be updated anytime.",
      primary: { label: "Add your venue", href: "/partner-workspace" },
      secondary: { label: "See the map", href: "/downtown-perks/explore" },
      footer: "No setup cost. You only give what the offer is worth.",
    },
  },
  brands: {
    id: "brands",
    label: "Brands",
    shortLabel: "Brands",
    route: "/partners/brands",
    mapMode: "brand",
    icon: Sparkles,
    eyebrow: "Brand Partner Layer",
    heroTitle: "Put your brand where people are already moving.",
    heroDescription: "Downtown Perks helps brands show up inside real downtown behavior — through buildings, venues, map context, district activity, and timed campaign moments that lead to measurable response.",
    heroPrimaryCta: { label: "Plan a campaign", href: "/partner-workspace" },
    heroSecondaryCta: { label: "See placement map", href: "/partners/dashboard" },
    heroStats: [
      { label: "Campaigns live", value: "12" },
      { label: "Total scans", value: "2.4K" },
      { label: "Visits", value: "840" },
      { label: "Redemptions", value: "340" },
    ],
    mapPreviewTitle: "Campaign preview",
    mapPreviewDescription: "Fine Eyewear Launch · The Paseo · District: Downtown",
    mapPreviewChips: ["340 Scans", "210 Visits", "58 Redeemed", "4 districts · Updated 2 min ago"],
    modulesTitle: "Campaign formats",
    modules: [
      { title: "Founding downtown partner", metric: "Always-on visibility", body: "Steady downtown presence across buildings, venues, and district context." },
      { title: "Launch campaign", metric: "Openings & seasonal", body: "New locations, timed campaigns, and moments that need concentrated attention." },
      { title: "Resident activation", metric: "Buildings & move-ins", body: "Building-led access for residents and high-intent local use cases." },
      { title: "Event-led campaign", metric: "Sponsorship & RSVPs", body: "Campaign logic tied to downtown events, venues, and RSVP momentum." },
      { title: "Utility-led campaign", metric: "Service & helpful", body: "Useful, place-aware campaigns that help someone do something in the moment." },
    ],
    stepsTitle: "How a downtown campaign turns into action.",
    workflow: [
      "Define the placement — Pick the districts, buildings, venues, and timing that shape the campaign.",
      "Launch the touchpoints — QR codes, map placements, venue surfaces, and district ties go live together.",
      "Show up in context — The campaign appears when someone nearby is already deciding what to do.",
      "People scan, save, and go — The interaction starts from a useful local moment, not a passive impression.",
      "See what converted — Scans, visits, saves, and redemptions are tracked by placement.",
    ],
    stepMetrics: ["Building QR → Map open → Save / tap → Visit → Redemption"],
    useCasesTitle: "See how campaigns come to life.",
    useCasesIntro: "A strong campaign should feel grounded in place, useful in the moment, and measurable after launch.",
    useCases: [
      { title: "Fine Eyewear × Downtown Perks", detail: "The Paseo + Map · Launch campaign for new location with QR integration. 340 scans · 210 visits · 58 redemptions · +12% this week" },
      { title: "Hotel Welcome Campaign", detail: "Hotel Van Zandt + Resident Buildings · Building-led resident activation with exclusive offer. 620 scans · 410 visits · 180 redemptions · +24% this week" },
      { title: "Downtown Weekend Activation", detail: "Multi-venue + District · Event-tied campaign across venues and outdoor spaces. 890 scans · 520 visits · 245 redemptions · +18% this week" },
    ],
    secondaryStats: [
      { label: "Scans", value: "2,400+" },
      { label: "Visits", value: "840+" },
      { label: "Redemptions", value: "340+" },
      { label: "Scan-to-visit", value: "68%" },
      { label: "Campaigns live", value: "12" },
      { label: "Districts active", value: "4" },
      { label: "Venue partners", value: "28" },
      { label: "Building access", value: "9" },
    ],
    liveActivityTitle: "Live campaign activity",
    liveActivity: [
      { title: "Resident scanned at The Quincy", meta: "Downtown Welcome", stamp: "Trending · 2 min ago" },
      { title: "Guest opened campaign from Hotel Van Zandt", meta: "Hotel Welcome", stamp: "5 min ago" },
      { title: "Visit recorded near Congress Avenue", meta: "Launch Campaign", stamp: "8 min ago" },
      { title: "Redemption completed in-store", meta: "Resident Activation", stamp: "12 min ago" },
      { title: "QR scanned at The Paseo building", meta: "Founding Partner", stamp: "15 min ago" },
      { title: "Event RSVP from downtown location", meta: "Event-led Campaign", stamp: "18 min ago" },
    ],
    form: {
      title: "Plan the campaign around the downtown moment.",
      intro: "Tell us what you want to achieve, where you want to show up, and what kind of response matters most. We will help map the right format, placements, and measurement plan.",
      roleOptions: ["Brand", "Property", "Venue", "Hotel"],
      fields: ["Your brand or organization", "Your name and role", "Phone", "What do you want this campaign to do?", "Describe your campaign goal..."],
      prompts: [
        "We want placement across real downtown locations",
        "Help us set up a QR-to-map flow",
        "Show us how a campaign connects to buildings and venues",
        "We want to track visits and redemptions by placement",
      ],
      submitLabel: "Submit campaign plan",
      recommendation: { title: "Based on your input", format: "Launch campaign", placements: "Map feature, QR moments, venue surfaces", metrics: "Scans, unlocks, visit pace, conversion" },
    },
    faqTitle: "Brand FAQs",
    faqIntro: "Brands use Downtown Perks to show up inside real downtown movement, not beside it.",
    faqs: [
      { id: "brand-1", question: "What kind of brand campaigns fit here?", answer: "Always-on presence, launch moments, building-led resident access, event-linked campaigns, and useful service-driven activations all fit the system." },
      { id: "brand-2", question: "How is this different from sponsorship placement?", answer: "Because the brand appears in context inside a place-aware action system rather than next to the action as passive media." },
      { id: "brand-3", question: "Can a brand connect to buildings and residents?", answer: "Yes. Buildings, hospitality partners, venues, and district layers can all act as campaign surfaces." },
      { id: "brand-4", question: "Can campaigns tie into events and districts?", answer: "Yes. That is one of the strongest reasons this page exists as a high-fidelity partner view." },
      { id: "brand-5", question: "What makes the Brands page the highest-fidelity page?", answer: "It shows the fullest version of placement, campaign logic, attribution, and measurable proof across the system." },
      { id: "brand-6", question: "What should a brand be able to measure?", answer: "Scans, visits, saves, redemptions, source placements, building response, and event-linked activity all matter." },
      { id: "brand-7", question: "How does Downtown Perks work with inKind?", answer: "inKind can remain part of offer or payment logic while Downtown Perks handles discovery, placement, and behavioral proof." },
    ],
    closing: {
      title: "Build the campaign around the downtown moment.",
      description: "Downtown Perks gives brands a way to show up inside live local behavior instead of sitting beside it. Start with the format that fits the objective, then connect placements, offer logic, and measurement into one downtown campaign system.",
      primary: { label: "Check availability", href: "/partner-workspace" },
      secondary: { label: "Become a partner", href: "/partners" },
      footer: "Questions? partners@downtownperks.com",
    },
  },
  civic: {
    id: "civic",
    label: "Civic",
    shortLabel: "Civic",
    route: "/partners/civic",
    mapMode: "civic",
    icon: Landmark,
    eyebrow: "Civic",
    heroTitle: "A civic layer built for how downtown actually works.",
    heroDescription: "Downtown Perks helps civic organizations surface events, districts, public moments, and local participation across one live downtown map. Make what is happening easier to find, easier to join, and easier to measure.",
    heroPrimaryCta: { label: "Explore civic formats", href: "/partners/dashboard" },
    heroSecondaryCta: { label: "View civic analytics", href: "/partners/dashboard" },
    heroStats: [
      { label: "Monthly opens", value: "28k+" },
      { label: "Active civic orgs", value: "8+" },
      { label: "RSVPs / month", value: "3.2k+" },
    ],
    mapPreviewTitle: "Civic Layer Preview",
    mapPreviewDescription: "Districts, events, and public participation",
    modulesTitle: "Civic formats for downtown participation",
    modules: [
      { title: "District visibility layer", metric: "Always-on civic presence", body: "Always-on civic presence across a neighborhood, district, or downtown corridor." },
      { title: "Event-led civic activation", metric: "Event-driven participation", body: "Festivals, downtown programs, public events, cultural moments, and RSVP-driven participation." },
      { title: "Neighborhood utility campaign", metric: "Useful public guidance", body: "Public-service information, wayfinding, recurring neighborhood tools, and useful downtown guidance." },
      { title: "Building and resident outreach layer", metric: "Resident and building outreach", body: "Move-ins, resident welcome flows, district education, local discovery, and recurring neighborhood participation." },
      { title: "Sponsored public moment", metric: "Sponsored activation", body: "Special downtown initiatives, seasonal programming, sponsored activations, and collaborative civic moments." },
    ],
    stepsTitle: "See how civic participation comes to life on the map",
    stepsIntro: "Civic partnerships in Downtown Perks should feel useful, timely, and easy to act on.",
    workflow: [
      "Choose the civic format that fits the district, moment, initiative, or public objective.",
      "Show it on the map where people are already looking.",
      "Connect buildings, events, venues, and public guidance into one live civic layer.",
      "Make participation easier to join in the moment.",
      "Measure opens, RSVPs, attributed visits, and repeat discovery.",
    ],
    useCasesTitle: "Which civic format is right?",
    useCasesIntro: "Select the format that matches your goal. We'll highlight the best fit.",
    useCases: [
      { title: "Always-on district presence", detail: "Steady district visibility and recurring civic context." },
      { title: "Event-driven participation", detail: "Programs, festivals, and public RSVP moments." },
      { title: "Resident and building outreach", detail: "Local education, welcome flows, and recurring neighborhood participation." },
      { title: "Useful public guidance", detail: "Wayfinding, utility, and information people actually need." },
    ],
    liveActivityTitle: "Proof & performance",
    liveActivity: [
      { title: "Map opens", meta: "+45% MoM", stamp: "28k+" },
      { title: "District engagement", meta: "+23% MoM", stamp: "14k+" },
      { title: "Event RSVPs", meta: "+67% MoM", stamp: "3.2k" },
      { title: "Attributed visits", meta: "+31% MoM", stamp: "8.4k" },
      { title: "Resident RSVP'd for Waterloo Greenway event", meta: "Event Marker", stamp: "5 min ago" },
      { title: "Downtown Austin Alliance district visibility updated", meta: "Admin", stamp: "34 min ago" },
      { title: "Visitor scanned Rainey Street wayfinding QR", meta: "District Utility", stamp: "1 hr ago" },
      { title: "Red River live event: 8 venues now showing", meta: "District", stamp: "3 hrs ago" },
      { title: "Wellness Loop: +12 new resident enrollments", meta: "Building Outreach", stamp: "4 hrs ago" },
      { title: "Visit Austin: +340 attributed downtown visits", meta: "Analytics", stamp: "6 hrs ago" },
    ],
    form: {
      title: "Ready to launch?",
      intro: "Tell us about your civic organization and we'll help you get up and running.",
      roleOptions: ["Property", "Hotel", "Venue", "Brand", "Civic"],
      fields: ["Organization / Property name"],
      submitLabel: "Get started",
      notes: "We'll be in touch within 24 hours to discuss your next steps.",
    },
    faqTitle: "Civic FAQs",
    faqIntro: "Civic partners use Downtown Perks to make what is happening downtown easier to find, easier to join, and easier to measure.",
    faqs: [
      { id: "civ-1", question: "How does civic fit into the Downtown Perks system?", answer: "Civic is one of the five partner views into the same map-based product. It uses the shared downtown layer to surface public moments, districts, events, and useful guidance." },
      { id: "civ-2", question: "What kinds of civic use cases belong here?", answer: "District visibility, cultural programs, public events, useful wayfinding, outreach, and other participation-oriented initiatives all fit here." },
      { id: "civ-3", question: "Can civic organizations appear on the map like other partners?", answer: "Yes. Civic layers use the same map system, but the content should feel public-serving and useful rather than commercial." },
      { id: "civ-4", question: "What should civic partners be able to measure?", answer: "Opens, RSVPs, participation, attributed visits, district engagement, and repeat discovery all matter." },
      { id: "civ-5", question: "Does this still feel public-facing rather than commercial?", answer: "Yes. The goal is to make what is happening easier to see and join, not to turn civic work into ad inventory." },
    ],
    closing: {
      title: "Build civic participation into the downtown moment.",
      description: "Downtown Perks gives civic organizations a way to show up inside live downtown behavior instead of outside it. Start with the format that fits the initiative, then connect visibility, participation, and proof into one civic system people can actually use.",
      primary: { label: "Check availability", href: "/partner-workspace" },
      secondary: { label: "Become a civic partner", href: "/partners" },
    },
  },
};

export const PARTNER_LANDING_SECTIONS = [
  {
    title: "Map-native discovery",
    body: "Residents, guests, and neighbors explore venues, events, and brands on a live map of downtown.",
    icon: Route,
  },
  {
    title: "Precise placement",
    body: "Your location, offer, or event appears contextually based on user intent and proximity.",
    icon: Users,
  },
  {
    title: "Real-time engagement",
    body: "Every interaction—scan, save, visit, redemption—is tracked and attributed.",
    icon: BarChart3,
  },
  {
    title: "Flexible models",
    body: "Launch campaigns, activate venues, connect residents, or drive foot traffic. Your choice.",
    icon: Megaphone,
  },
];

export const PARTNER_PLATFORM_MODULES = [
  { title: "Active partners", body: "40+" },
  { title: "Monthly scans", body: "180k" },
  { title: "Avg retention", body: "52%" },
  { title: "Campaign ROI", body: "3.2x" },
  { title: "Total reach", body: "120k" },
  { title: "Redemption rate", body: "28%" },
];

export const PARTNER_ROLE_PROOF = [
  { type: "Residential", name: "The Paseo", summary: "Residents discovered local venues 3x more after launch", proof: "↑ 180% engagement", href: "/partners/residential" },
  { type: "Hospitality", name: "Hotel Van Zandt", summary: "Guest foot traffic to nearby venues increased 2.1x", proof: "↑ 84 visits/week", href: "/partners/hospitality" },
  { type: "Venues", name: "Banger's", summary: "Consistent foot traffic and repeat visits from map discovery", proof: "↑ 41% return rate", href: "/partners/venues" },
];

export const PARTNER_PROGRAM_FAQS = [
  { id: "pp-1", question: "Are these separate products or one shared system?", answer: "It is one shared system. Residential, hospitality, venues, brands, and civic all connect through the same map, action model, and proof layer." },
  { id: "pp-2", question: "Why were Properties removed from the main taxonomy?", answer: "Because Residential is the clearer user-facing label. The route can still preserve compatibility, but the partner taxonomy should read as Residential, Hospitality, Venues, Brands, and Civic." },
  { id: "pp-3", question: "What does each partner type get?", answer: "Each type gets a map-linked surface, role-specific measurement, and a path into the shared dashboard and workspace." },
  { id: "pp-4", question: "What actions can users take?", answer: "Browse, save, RSVP, visit, redeem, and interact through scans or contextual prompts depending on the partner surface." },
  { id: "pp-5", question: "How do examples work?", answer: "Examples show how the system behaves in practice, but the partner pages should stay general enough to explain the model clearly before brand-specific proof." },
  { id: "pp-6", question: "Why is Brands the reference page?", answer: "Because it shows the fullest version of placement, campaign logic, attribution, and measurable response across the downtown system." },
  { id: "pp-7", question: "What makes this credible?", answer: "A live map, clear partner types, measured actions, and pages that explain exactly what the partner gets and what gets tracked." },
  { id: "pp-8", question: "What should this feel like?", answer: "One system, five roles. Operational, measurable, and grounded in real downtown movement." },
];

export const BRAND_SHOWCASE_GROUPS = [
  {
    id: "campaign",
    label: "Campaign showcase",
    description: "Examples for brand and activation pitches. These are optional references, not the core partner narrative.",
    items: [
      { name: "The Paseo", route: "/brands/the-paseo", summary: "Residential-linked campaign surface with building entry and nearby perk visibility." },
      { name: "Hotel Van Zandt", route: "/brands/hotel-van-zandt", summary: "Hospitality-led activation showing guest flow into local venues and events." },
      { name: "YETI", route: "/brands/yeti", summary: "Branded downtown activation with timing, source tracking, and event tie-ins." },
    ],
  },
  {
    id: "district",
    label: "District and venue showcase",
    description: "Use when the pitch needs contextual proof across places, properties, and downtown corridors.",
    items: [
      { name: "Banger's", route: "/brands/bangers", summary: "Venue example for map-native conversion and repeat local discovery." },
      { name: "Four Seasons Residences", route: "/brands/four-seasons-residences", summary: "Residential example connecting building value to walkable downtown relevance." },
      { name: "Waterline", route: "/brands/the-waterline", summary: "Mixed-use example showing premium positioning and neighborhood utility together." },
    ],
  },
];

export const PARTNER_DASHBOARD_LINK = "/partners/dashboard";
