export const collectionBriefMeta = {
  label: "CONFIDENTIAL BRIEF",
  title: "Downtown Perks Launch Brief for Nina",
  subtitle: "A relationship-led launch plan for Nina Seely",
  preparedFor: "Nina Seely",
  organization: "Legends Real Estate",
  location: "Downtown Austin",
  date: "July 2026",
  coreDecision: "Begin with Nina’s strongest relationships. A few trusted introductions can put Downtown Perks in front of the right partners quickly and credibly.",
  objective: "In the first 60 days, secure two building routes, one hospitality group, one hotel, one civic partner, and one referral or media partner.",
};

const warmOnly = "Warm relationship supplied in the confidential brief; direct email and phone were not supplied.";
const researchOnly = "Research required. Confirm the current decision-maker, operating owner, direct contact route, and participating assets before outreach.";

export const collectionTargetDirectory = [
  {
    id: "worth-ross",
    priority: "1",
    name: "Worth Ross / WRMC",
    segment: "Residential portfolio",
    relationshipStrength: "Warm",
    pageStatus: "Partially ready",
    why: "One portfolio relationship can open several downtown condo communities and create a repeatable HOA-style pilot path.",
    pilot: "One downtown condo community, one accountable community manager, and a written route to two follow-on buildings.",
    assets: ["44 East", "70 Rainey", "900 S. 1st", "Downtown condo / HOA portfolio — current management scope to confirm"],
    assetNote: "These are proposed pilot candidates and relationship scope, not a current ownership or management claim until reconfirmed.",
    contacts: [
      { name: "SaraMarie Blunt", role: "Warm Worth Ross relationship; current role to confirm", status: "Warm", channel: warmOnly },
      { name: "Jack Thuet", role: "Warm Worth Ross routing contact; current role to confirm", status: "Warm", channel: warmOnly },
      { name: "Rikki Conner", role: "Warm Worth Ross relationship; current role to confirm", status: "Warm", channel: warmOnly },
      { name: "Kasidy Schaub", role: "Proposed Austin regional route; title and scope to verify", status: "Research required", channel: "Use a documented warm introduction or the official company route." },
      { name: "Andrea Willett", role: "Proposed executive escalation; current title and authority to verify", status: "Research required", channel: "Use a documented warm introduction or the official company route." },
      { name: "WRMC Association Portal", role: "Current official support route", email: "info4hoa@worthross.com", phone: "855-435-4596", status: "Confirmed company channel" },
    ],
    preparedPages: ["SaraMarie Blunt", "Rikki Conner", "Jack Thuet identified", "Worth Ross portfolio operations — proposed"],
    missingPages: ["Current Austin portfolio lead", "Selected pilot building owner / board route"],
    nextAction: "Ask SaraMarie, Jack, or Rikki which downtown community is easiest to start with, then confirm the portfolio lead, community manager, and board approval path.",
    ask: "Could you help us choose one pilot-ready Worth Ross community, name the person who would run it, and confirm the path to two additional buildings if the first test performs?",
    sources: [["Worth Ross", "https://worthross.com/"], ["WRMC portal help", "https://home.worthross.com/Home_v2/Help"]],
  },
  {
    id: "greystar-paseo",
    priority: "1",
    name: "Greystar / Paseo",
    segment: "Residential portfolio",
    relationshipStrength: "Warm / introduced",
    pageStatus: "Ready with verification",
    why: "Paseo offers a realistic first residential proof point with a potential Austin portfolio expansion path.",
    pilot: "One Paseo resident communication, one lobby QR touchpoint, one 30-day recap, and one named follow-on property.",
    assets: ["Paseo", "Greystar Austin portfolio pathway", "Resident communications", "Onsite leasing and property operations"],
    assetNote: "Paseo is the proposed proof property. Any follow-on Greystar assets must be named by the regional team.",
    contacts: [
      { name: "Renee Zahn", role: "Managing Director, Property Management, Central West", status: "Current public leadership route", channel: "Use the Greystar leadership page or a documented introduction." },
      { name: "Nirosha Perera", role: "Supplied Paseo GM route; current title and property scope to reconfirm", status: "Supplied working contact", channel: warmOnly },
      { name: "Jarrod Byer", role: "Supplied Paseo property-management route; current role to reconfirm", status: "Supplied working contact", channel: warmOnly },
      { name: "Ana Cunningham", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "Brenda Holden", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "Cody Newton", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "Dominique Saldana", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "Hannah Cummings", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "James Matta", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "Melissa Rhoades", role: "Greystar contact page prepared; current scope to confirm", status: "Prepared contact page", channel: "Use the prepared page and confirm current portfolio relevance." },
      { name: "Paseo Leasing", role: "Property contact route", email: "leasing@paseoatx.com", phone: "512-856-5117", status: "Property channel" },
      { name: "Greystar Property Route", role: "Supplied property phone", phone: "737-738-8129", status: "Supplied working route" },
    ],
    preparedPages: ["Paseo", "Ana Cunningham", "Brenda Holden", "Cody Newton", "Dominique Saldana", "Hannah Cummings", "James Matta", "Jarrod Byer", "Melissa Rhoades"],
    missingPages: ["Nirosha Perera / current Paseo GM — confirm", "Regional expansion approver"],
    nextAction: "Confirm the Paseo signer, resident-communications owner, onsite operator, legal/vendor review, and the regional person who can approve the next building.",
    ask: "Could you introduce us to the person who can approve a small Paseo pilot and tell us who would handle the next Austin building if it works?",
    sources: [["Greystar — Renee Zahn", "https://www.greystar.com/contact-us/our-people/renee-zahn"], ["Paseo", "https://www.greystar.com/properties/austin-tx/paseo"]],
  },
  {
    id: "lv-collective",
    priority: "1",
    name: "LV Collective",
    segment: "Residential owner / placemaking",
    relationshipStrength: "Research required",
    pageStatus: "Needs dedicated page",
    why: "LV can sponsor the ownership and brand side of a joint Paseo pilot while Greystar manages onsite execution.",
    pilot: "Joint Paseo ownership sponsorship, brand alignment, and an agreed expansion criterion.",
    assets: ["Paseo", "Lifestyle residential portfolio", "Brand and placemaking relationships"],
    assetNote: "The first scope is Paseo. Other LV properties should not be included until the portfolio team names them.",
    contacts: [
      { name: "Jonathan Reyes", role: "President", status: "Current public leadership route", channel: "Use the LV Collective leadership page or a documented introduction." },
      { name: "Kendall Guinn", role: "Chief Marketing Officer — supplied route; current scope to confirm", status: "Supplied working route", channel: researchOnly },
      { name: "Louie Colella", role: "SVP, Property Management", status: "Current public leadership route", channel: "Use the LV Collective leadership page or a documented introduction." },
      { name: "LV Collective Office", role: "Company phone", phone: "512-410-0342", status: "Company route" },
    ],
    preparedPages: [],
    missingPages: ["LV Collective portfolio page", "Paseo ownership / brand decision page"],
    nextAction: "Confirm who signs for LV, who owns brand alignment, and how LV and Greystar divide legal, communications, and reporting responsibilities.",
    ask: "Who can approve LV’s side of a joint Paseo pilot and appoint the owner for brand, property-management, and expansion decisions?",
    sources: [["LV Collective — Jonathan Reyes", "https://lvcollective.com/team/jonathan-reyes/"], ["LV Collective — Louie Colella", "https://lvcollective.com/team/louie-colella/"]],
  },
  {
    id: "endeavor",
    priority: "1",
    name: "Endeavor Real Estate Group",
    segment: "Developer / commercial relationship",
    relationshipStrength: "Warm",
    pageStatus: "Needs page / confirm current asset scope",
    why: "Endeavor is a high-value relationship opener into downtown development, leasing, retail, and Frost Bank Tower history.",
    pilot: "Use the Endeavor relationship to reach the current accountable Frost Bank Tower asset and operating team.",
    assets: ["Frost Bank Tower relationship opener", "The Quincy", "Saltillo", "Statesman-related development relationships", "Retail and leasing network"],
    assetNote: "Endeavor is treated as the opening relationship, not automatically as the current Frost Bank Tower approval owner.",
    contacts: [
      { name: "Travis Dunaway", role: "First warm route", status: "Named public route", channel: "Use the Endeavor team page or Nina’s relationship route." },
      { name: "Anne Swift", role: "Executive / development contact — exact current scope to confirm", status: "Supplied working contact", channel: warmOnly },
      { name: "Colton McCasland", role: "Development contact — exact current scope to confirm", status: "Supplied working contact", channel: warmOnly },
      { name: "Connor Lammert", role: "Vice President, Retail Leasing — supplied title; reconfirm", status: "Supplied working contact", channel: warmOnly },
      { name: "Evan Deitch", role: "Senior Vice President, Retail Leasing — supplied title; reconfirm", status: "Supplied working contact", channel: warmOnly },
      { name: "Dana Gann", role: "Senior Property Manager — supplied Frost route; reconfirm current asset", status: "Supplied working contact", channel: warmOnly },
    ],
    preparedPages: ["Travis Dunaway team page"],
    missingPages: ["Endeavor portfolio page", "Frost Bank Tower current decision page"],
    nextAction: "Ask Travis to identify the current Frost Bank Tower asset owner, property manager, tenant-experience lead, and communications authority.",
    ask: "Could you introduce us to the current person who can approve a focused Frost Bank Tower tenant-experience pilot and appoint the operating owner?",
    sources: [["Travis Dunaway", "https://www.endeavor-re.com/about/team/travis-dunaway/"]],
  },
  {
    id: "divcowest",
    priority: "1",
    name: "DivcoWest",
    segment: "Commercial property owner / asset management",
    relationshipStrength: "Research required",
    pageStatus: "Needs page",
    why: "DivcoWest is the current route to confirm Frost Bank Tower asset authority, tenant experience, property operations, and communications.",
    pilot: "One Frost Bank Tower employee and tenant discovery pilot with a lobby QR, one communication, and a 30-day recap.",
    assets: ["Frost Bank Tower", "Austin office portfolio", "Tenant experience", "Leasing and property-management relationships"],
    assetNote: "Asset-specific authority and the current property-management chain must be confirmed directly.",
    contacts: [
      { name: "Gregg Walker", role: "President, Real Estate Asset Management", status: "Current public leadership route", channel: "Use the DivcoWest people page and corporate office." },
      { name: "Jack Bossung", role: "Associate Director, Investments, Austin", status: "Current public Austin route", channel: "Use the DivcoWest people page and corporate office." },
      { name: "Tina Snyder", role: "Senior Director, Head of Marketing", status: "Current public leadership route", channel: "Use the DivcoWest people page and corporate office." },
      { name: "DivcoWest Corporate", role: "Company phone", phone: "415-284-5700", status: "Company route" },
    ],
    preparedPages: [],
    missingPages: ["DivcoWest partner page", "Frost Bank Tower asset / tenant-experience page"],
    nextAction: "Confirm the Frost asset decision-maker, current property manager, tenant-experience owner, and tenant communications channel.",
    ask: "Who currently owns approval for a single-building tenant-experience pilot at Frost Bank Tower, and who would run communications and reporting?",
    sources: [["DivcoWest people", "https://divcowest.com/people/"], ["DivcoWest Austin office", "https://divcowest.com/company/about-us/"]],
  },
  {
    id: "lincoln-property-company",
    priority: "2",
    name: "Lincoln Property Company",
    segment: "Commercial / mixed-use portfolio",
    relationshipStrength: "Supplied contact routes",
    pageStatus: "Needs page",
    why: "One Lincoln relationship could open an occupied office or mixed-use property with an established tenant communications path.",
    pilot: "One occupied-asset tenant or resident discovery pilot with a named operator and report date.",
    assets: ["Austin mixed-use relationships", "Office assets", "Tenant experience", "Commercial leasing network"],
    assetNote: "No specific Lincoln asset is assigned until the Austin team selects one.",
    contacts: [
      { name: "Mark Miller", role: "Supplied Lincoln contact; exact current title and scope to reconfirm", email: "MMiller@LPC.com", status: "Supplied working route" },
      { name: "Seth Johnston", role: "Supplied Lincoln contact; exact current title and scope to reconfirm", email: "SJohnston@LPC.com", status: "Supplied working route" },
      { name: "Trish Williams", role: "Supplied Lincoln contact; exact current title and scope to reconfirm", email: "TRWilliams@LPC.com", status: "Supplied working route" },
    ],
    preparedPages: [],
    missingPages: ["Lincoln Property Company target page", "Selected occupied asset page"],
    nextAction: "Reconfirm the three supplied contacts and ask which Austin asset has the cleanest approval and communications path.",
    ask: "Who can approve one occupied-asset pilot and appoint the property or tenant-experience operator?",
    sources: [["Lincoln Property Company", "https://www.lincolnpropertycompany.com/"]],
  },
  {
    id: "rainey-street-coalition",
    priority: "1",
    name: "Rainey Street Coalition",
    segment: "District coalition",
    relationshipStrength: "Research required",
    pageStatus: "Parent page required",
    why: "A coalition route can create district credibility and unlock several operators through one conversation.",
    pilot: "A Founding Partner meeting followed by one or two coalition-backed venue activations.",
    assets: ["Coalition members", "Rainey operating network", "District events", "Historical and current operator relationships"],
    assetNote: "Current coalition membership, leadership, and operating authority must be verified. Historical district figures are context, not automatic outreach contacts.",
    contacts: [
      { name: "Current founder / executive", role: "Coalition approver", status: "Research required", channel: researchOnly },
      { name: "Current board and active operators", role: "Operating and distribution routes", status: "Research required", channel: researchOnly },
      { name: "Bridget Dunlap", role: "Historical Rainey context and active operator relationship", status: "Context / warm route", channel: warmOnly },
      { name: "Jesse Lunsford", role: "Historical district context; outreach relevance to confirm", status: "Context only", channel: warmOnly },
      { name: "Dale Glover", role: "Historical district context; outreach relevance to confirm", status: "Context only", channel: warmOnly },
    ],
    preparedPages: ["Rainey Street Historic District", "Rainey After-Work Dining Push", "Individual venue pages"],
    missingPages: ["Rainey Street Coalition parent page", "Current executive / decision-maker page"],
    nextAction: "Verify the current coalition leader and one operator sponsor before requesting a Founding Partner meeting.",
    ask: "Who currently speaks for the coalition and can sponsor one or two operator pilots?",
    sources: [],
  },
  {
    id: "rainey-ventures",
    priority: "2",
    name: "Rainey Ventures",
    segment: "Rainey corridor relationship",
    relationshipStrength: "Research required",
    pageStatus: "Parent page required",
    why: "A Rainey portfolio relationship can unlock several nearby venues and events without selling one venue at a time.",
    pilot: "One or two Rainey venues with a shared district story and one operating owner.",
    assets: ["Amaya", "Daydreamer Coffee", "Banger’s", "Clive Bar", "Emmer & Rye", "Geraldine’s", "Half Step", "Lucille", "Lustre Pearl", "Stay Put", "The Rainey House", "CorePower Yoga Downtown Austin", "Rainey Street Historic District"],
    assetNote: "The list reflects drafted corridor pages and launch scope. Ownership or affiliation with Rainey Ventures must be confirmed per venue.",
    contacts: [{ name: "Current Rainey Ventures executive", role: "Portfolio / corridor decision-maker", status: "Research required", channel: researchOnly }],
    preparedPages: ["Amaya", "Daydreamer Coffee", "Banger’s", "Clive Bar", "Emmer & Rye", "Geraldine’s", "Half Step", "Lucille", "Lustre Pearl", "Stay Put", "The Rainey House", "CorePower Yoga Downtown Austin", "Rainey Street Historic District"],
    missingPages: ["Rainey Ventures parent page", "Current decision-maker page"],
    nextAction: "Verify the parent organization, current executive, and which prepared venues are actually in scope.",
    ask: "Who can approve a small two-venue Rainey pilot and appoint one operator for execution?",
    sources: [],
  },
  {
    id: "dunlap-atx",
    priority: "1",
    name: "Dunlap ATX",
    segment: "Hospitality portfolio",
    relationshipStrength: "Existing / warm",
    pageStatus: "Needs parent page",
    why: "A founder-level conversation can unlock several Rainey concepts with one operating and reporting owner.",
    pilot: "Begin with Lustre Pearl and Lucille, or the two concepts Bridget identifies as most ready.",
    assets: ["Lustre Pearl", "Lucille", "Clive", "Container Bar", "Vida Lee", "Lil’ Mama", "Parlor & Yard", "Other active concepts — confirm"],
    assetNote: "Active concepts and venue ownership should be reconfirmed immediately before outreach.",
    contacts: [
      { name: "Bridget Dunlap", role: "Founder / principal relationship route", email: "bridget@dunlapatx.com", status: "Supplied working route — reconfirm" },
      { name: "Chris Parker", role: "Supplied target contact; current Dunlap affiliation and role to verify", status: "Research required", channel: warmOnly },
      { name: "Clive Management", role: "Venue operations route", email: "clivemgmt@dunlapatx.com", status: "Supplied working route — reconfirm" },
      { name: "Lustre Pearl East Management", role: "Venue operations route", email: "lpemgmt@dunlapatx.com", phone: "512-524-1143", status: "Supplied working route — reconfirm" },
    ],
    preparedPages: ["Lustre Pearl", "Lucille", "Clive", "Container Bar-related corridor assets"],
    missingPages: ["Dunlap ATX parent page", "Portfolio decision-maker / operating owner page"],
    nextAction: "Ask Bridget which two concepts are operationally strongest and who should coordinate the pilot across them.",
    ask: "Could we start with two concepts and appoint one person to coordinate the staff plan and 30-day recap?",
    sources: [["Dunlap ATX contact", "https://dunlapatx.com/contact/"]],
  },
  {
    id: "mml-hospitality",
    priority: "1",
    name: "MML Hospitality",
    segment: "Hospitality portfolio",
    relationshipStrength: "Target",
    pageStatus: "Needs portfolio page",
    why: "One executive conversation can curate several high-recognition Austin concepts into a coherent resident collection.",
    pilot: "Three to five downtown-relevant concepts with one portfolio marketing or operations owner.",
    assets: ["Jeffrey’s", "Josephine House", "Clark’s", "Perla’s", "June’s", "Sammie’s", "Swedish Hill", "Elizabeth Street Café", "Hotel Magdalena", "Hotel Saint Cecilia"],
    assetNote: "Concept ownership, current operating status, and downtown relevance should be reconfirmed before proposing the final set.",
    contacts: [
      { name: "Larry McGuire", role: "Founder / executive route", status: "Named target", channel: warmOnly },
      { name: "Tom Moorman", role: "Executive route", status: "Named target", channel: warmOnly },
      { name: "Liz Lambert", role: "Relevant hotel / hospitality relationship where appropriate", status: "Related route", channel: warmOnly },
      { name: "Portfolio operations / marketing owner", role: "Day-to-day execution", status: "To identify", channel: researchOnly },
    ],
    preparedPages: [],
    missingPages: ["MML Hospitality portfolio invitation", "Selected concept pages / operating contacts"],
    nextAction: "Confirm the executive opening route, select three to five concepts, and appoint one portfolio owner.",
    ask: "Could we curate a three-to-five concept resident collection and name one person to run it across the portfolio?",
    sources: [],
  },
  {
    id: "emmer-rye-hospitality",
    priority: "1",
    name: "Emmer & Rye Hospitality Group",
    segment: "Chef-led hospitality portfolio",
    relationshipStrength: "Target",
    pageStatus: "Venue pages ready; parent page to confirm",
    why: "A chef-led collection can combine neighborhood discovery, events, and repeat local use under one portfolio conversation.",
    pilot: "A small resident collection plus one event hook across selected concepts.",
    assets: ["Emmer & Rye", "Hestia", "Canje", "Ezov", "Kalimotxo", "Ladino"],
    assetNote: "Final participation, current concept list, and location-level owners require confirmation.",
    contacts: [
      { name: "Kevin Fink", role: "Founder / executive route", status: "Named target", channel: warmOnly },
      { name: "Tavel Bristol-Joseph", role: "Founder / culinary executive route", status: "Named target", channel: warmOnly },
      { name: "Portfolio operations / marketing", role: "Execution owner", status: "To identify", channel: researchOnly },
      { name: "Individual venue GMs", role: "Location execution", status: "To identify", channel: researchOnly },
    ],
    preparedPages: ["Emmer & Rye", "Selected Rainey and restaurant venue pages"],
    missingPages: ["Emmer & Rye Hospitality parent page", "Portfolio owner / selected GM pages"],
    nextAction: "Choose the smallest coherent concept set and identify one portfolio operating owner.",
    ask: "Could we approve a chef-led resident collection and one event pilot with one accountable portfolio owner?",
    sources: [],
  },
  {
    id: "guy-larry-restaurants",
    priority: "1",
    name: "Guy + Larry Restaurants",
    segment: "Restaurant group",
    relationshipStrength: "Warm",
    pageStatus: "Needs page",
    why: "One group conversation can support a measurable dining passport or resident collection across several downtown concepts.",
    pilot: "Two to four concepts, one group marketing or operations lead, and one 30-day behavior recap.",
    assets: ["ATX Cocina", "Red Ash", "J. Carver’s", "Restaurant François", "Bar Rouge"],
    assetNote: "Current concept ownership, operating status, and François / Bar Rouge structure should be confirmed before outreach.",
    contacts: [
      { name: "Guy Villavaso", role: "Founder / executive route", status: "Warm target", channel: warmOnly },
      { name: "Larry Foles", role: "Founder / executive route", status: "Warm target", channel: warmOnly },
      { name: "Carrie Gallagher", role: "Supplied related contact; current affiliation to verify", status: "Research required", channel: warmOnly },
      { name: "Group operations / marketing lead", role: "Day-to-day owner", status: "To identify", channel: researchOnly },
    ],
    preparedPages: ["Individual restaurant and dining-passport assets in the workspace"],
    missingPages: ["Guy + Larry Restaurants parent page", "Group marketing / operations owner page"],
    nextAction: "Confirm the executive route, select two to four concepts, and identify one group operating owner.",
    ask: "Could you introduce us to Guy, Larry, or the person on their team who could test this with two to four restaurants?",
    sources: [],
  },
  {
    id: "new-waterloo",
    priority: "1",
    name: "New Waterloo",
    segment: "Hotel + dining portfolio",
    relationshipStrength: "Research required",
    pageStatus: "Needs portfolio page",
    why: "One portfolio relationship can connect a hotel, dining, guest communications, and local loyalty experience.",
    pilot: "South Congress Hotel plus Café No Sé, with one portfolio approver and one property operating lead.",
    assets: ["South Congress Hotel", "Carpenter Hotel", "Albert Hotel", "Café No Sé", "Mañana", "La Condesa", "Central Machine Works"],
    assetNote: "Select one hotel-plus-dining proof set first; do not imply participation by the wider portfolio until approved.",
    contacts: [
      { name: "Bart Knaggs", role: "Chief Executive Officer + Partner", status: "Current public leadership route", channel: "Use the New Waterloo team page or a warm introduction." },
      { name: "Leigh Hitz", role: "Chief Operations Officer", status: "Current public leadership route", channel: "Use the New Waterloo team page or a warm introduction." },
      { name: "Sarah Swenson", role: "Corporate Director of Marketing", status: "Current public operating route", channel: "Use the New Waterloo team page or a warm introduction." },
      { name: "Mindi Marshall", role: "Corporate Director of Hotel Operations", status: "Current public operating route", channel: "Use the New Waterloo team page or a warm introduction." },
      { name: "South Congress Hotel property lead", role: "Location owner", status: "To identify", channel: researchOnly },
    ],
    preparedPages: [],
    missingPages: ["New Waterloo portfolio invitation", "South Congress Hotel property-owner page", "Café No Sé operating page"],
    nextAction: "Confirm Nina’s warmest New Waterloo route, the current South Congress Hotel property lead, and one local experience.",
    ask: "Who can approve a South Congress Hotel plus Café No Sé pilot, and who should own launch, distribution, and reporting?",
    sources: [["New Waterloo team", "https://newwaterloo.com/who-we-are/our-team"]],
  },
  {
    id: "white-lodging",
    priority: "2",
    name: "White Lodging",
    segment: "Hotel + food and beverage",
    relationshipStrength: "Research required",
    pageStatus: "Needs portfolio page",
    why: "A hotel-led pilot can connect guest discovery with local resident dining and event behavior.",
    pilot: "Austin Marriott Downtown plus Corinne and Zanzibar; treat Dean’s as a separate JW Marriott expansion route.",
    assets: ["Austin Marriott Downtown", "Corinne", "Zanzibar", "JW Marriott Austin — separate expansion", "Dean’s Italian Steakhouse — separate expansion"],
    assetNote: "Dean’s is not inside Austin Marriott Downtown. Keep the first Austin Marriott scope separate from the JW Marriott expansion path.",
    contacts: [
      { name: "David Meisner", role: "Regional Vice President", status: "Current public regional route", channel: "Use the White Lodging leadership route or a warm introduction." },
      { name: "Thomas Hoffmann", role: "Vice President and General Manager, Austin Marriott Downtown", status: "Current public property route", channel: "Use the Austin Marriott Downtown official route." },
      { name: "Austin Marriott Downtown", role: "Hotel main line", phone: "512-457-1111", status: "Official property route" },
      { name: "Hotel marketing lead", role: "Execution owner", status: "To identify", channel: researchOnly },
      { name: "Food-and-beverage lead", role: "Execution owner", status: "To identify", channel: researchOnly },
    ],
    preparedPages: [],
    missingPages: ["White Lodging portfolio invitation", "Austin Marriott + Corinne + Zanzibar pilot page"],
    nextAction: "Name the marketing and F&B owners and confirm scope, legal review, distribution, and reporting.",
    ask: "Could you identify the person who can approve one Austin Marriott Downtown local-discovery pilot and appoint the marketing and F&B owners?",
    sources: [["Austin Marriott Downtown", "https://www.marriott.com/en-us/hotels/ausmd-austin-marriott-downtown/overview/"]],
  },
  {
    id: "hai-hospitality",
    priority: "2",
    name: "Hai Hospitality",
    segment: "Hospitality portfolio",
    relationshipStrength: "Target",
    pageStatus: "Needs portfolio page",
    why: "Uchibā is a strong downtown anchor with a clear route to a broader Hai collection if the first pilot works.",
    pilot: "Uchibā-first resident pilot, one brand and operations owner, and one expansion criterion.",
    assets: ["Uchi", "Uchiko", "Uchibā", "Loro"],
    assetNote: "Uchibā is the downtown-core anchor. The broader concepts are expansion possibilities, not one automatic downtown collection.",
    contacts: [
      { name: "Tony Montero", role: "Chief Executive Officer", status: "Current public leadership route", channel: "Use Hai’s leadership page or a warm introduction." },
      { name: "Tyson Cole", role: "Founder-level sponsor", status: "Named relationship route; sponsorship path to confirm", channel: warmOnly },
      { name: "Amber Quist", role: "Chief Brand Officer", status: "Current public operating route", channel: "Use Hai’s leadership page or a warm introduction." },
      { name: "Leo Barrera", role: "Vice President of Operations", status: "Current public operating route", channel: "Use Hai’s leadership page or a warm introduction." },
      { name: "Hai Hospitality", role: "Company inbox", email: "info@haihospitality.com", status: "Company route" },
      { name: "Uchibā Austin", role: "Property phone", phone: "512-916-4808", status: "Property route" },
    ],
    preparedPages: [],
    missingPages: ["Hai Hospitality portfolio invitation", "Uchibā pilot page"],
    nextAction: "Confirm the Uchibā experience, the accountable execution owner, and the evidence required for portfolio expansion.",
    ask: "Who can approve an Uchibā-first pilot and own the experience, operations, and 30-day results review?",
    sources: [["Hai Hospitality leadership", "https://www.haihospitality.com/about"], ["Uchibā Austin", "https://uchiba.uchirestaurants.com/location/austin/"]],
  },
  {
    id: "lobo-hospitality",
    priority: "2",
    name: "Lobo Hospitality",
    segment: "Hospitality operator",
    relationshipStrength: "Warm",
    pageStatus: "Needs inventory confirmation",
    why: "Nina has two warm contacts who can identify the easiest active concept and the correct operator.",
    pilot: "One active Lobo concept with a simple resident offer or event and one operator owner.",
    assets: ["Lobo Hospitality active concepts — exact current list to confirm", "Operator relationships"],
    assetNote: "Do not publish or outreach with a concept list until Tiffany or Grace confirms the active portfolio.",
    contacts: [
      { name: "Tiffany Matthews", role: "Warm Lobo Hospitality route", status: "Warm", channel: warmOnly },
      { name: "Grace Chow", role: "Warm Lobo Hospitality route", status: "Warm", channel: warmOnly },
    ],
    preparedPages: [],
    missingPages: ["Lobo Hospitality parent page", "Selected active concept page", "Current operator page"],
    nextAction: "Ask Tiffany or Grace which active concept is easiest for a small resident offer or event and who can approve it.",
    ask: "Which Lobo concept is most realistic for a simple first test, and who should own it?",
    sources: [],
  },
  {
    id: "inkind",
    priority: "1",
    name: "inKind",
    segment: "Dining platform / partner network",
    relationshipStrength: "Target / warm route preferred",
    pageStatus: "Partner layer ready",
    why: "A verified inKind cohort can add dining density through one platform relationship without treating every restaurant as a participant.",
    pilot: "Five to ten explicitly verified downtown venues, one Austin partnerships owner, and one account owner.",
    assets: ["Verified five-to-ten venue downtown cohort", "Current product test cohort: J. Carver’s, Péché, Parkside, Burger Bar Congress — reconfirm program participation", "inKind partner layer"],
    assetNote: "inKind is an optional program layer. Only venues with explicit current evidence should be included.",
    contacts: [
      { name: "Johann Moonesinghe", role: "Founder and CEO", status: "Current public leadership route", channel: "Warm introduction preferred." },
      { name: "Steph “SJ” Carcamo", role: "Proposed partnerships / marketing route; current title to confirm", status: "Research required", channel: warmOnly },
      { name: "inKind Support", role: "Supplied working inbox", email: "support@inkind.com", status: "Supplied route — reconfirm" },
      { name: "inKind Impact", role: "Supplied social-impact inbox", email: "impact@inkind.com", status: "Supplied route — reconfirm" },
    ],
    preparedPages: ["inKind Partner Layer"],
    missingPages: ["Current Austin partnerships owner", "Final approved cohort page"],
    nextAction: "Confirm cohort authority, current participating venues, one account owner, and reporting expectations.",
    ask: "Could we align on a clearly verified five-to-ten venue downtown cohort and one accountable Austin owner?",
    sources: [["inKind about", "https://inkind.com/about"], ["inKind support", "https://inkind.com/how-to-contact-inkind-support"]],
  },
  {
    id: "hotel-van-zandt",
    priority: "1",
    name: "Hotel Van Zandt",
    segment: "Hotel anchor",
    relationshipStrength: "Target",
    pageStatus: "Ready",
    why: "The hotel can test a resident-local activation that connects rooms, dining, events, and the Rainey audience.",
    pilot: "One local offer or event with Hotel Van Zandt and Geraldine’s, supported by one guest or resident distribution path.",
    assets: ["Hotel Van Zandt", "Geraldine’s", "First Thursday at Hotel Van Zandt", "Rainey guest and local audience"],
    assetNote: "Confirm the current GM, marketing, sales, and F&B owners before outreach.",
    contacts: [
      { name: "Current Hotel Van Zandt GM", role: "Property approver", status: "Research required", channel: researchOnly },
      { name: "Marketing / sales lead", role: "Distribution and promotion", status: "Research required", channel: researchOnly },
      { name: "Food-and-beverage lead", role: "Geraldine’s and event execution", status: "Research required", channel: researchOnly },
    ],
    preparedPages: ["Hotel Van Zandt", "First Thursday at Hotel Van Zandt"],
    missingPages: ["Current GM / marketing / F&B contact page"],
    nextAction: "Identify the current hotel approver and one marketing or F&B owner for a local-first activation.",
    ask: "Who could help us test one local offer or event with Hotel Van Zandt and Geraldine’s?",
    sources: [],
  },
  {
    id: "kmg-hotels",
    priority: "2",
    name: "KMG Hotels",
    segment: "Hotel network",
    relationshipStrength: "Warm",
    pageStatus: "Research required",
    why: "A warm hotel relationship can identify the Austin property with the cleanest GM, marketing, sales, and F&B approval path.",
    pilot: "One Austin hotel, one local offer or event, and one property operator.",
    assets: ["KMG Austin hotel relationships — exact properties to confirm", "GM, marketing, sales, and F&B network"],
    assetNote: "The confidential brief does not identify the exact KMG Austin properties. Confirm before creating partner pages.",
    contacts: [{ name: "Kristie Braley", role: "Warm KMG Hotels route", status: "Warm", channel: warmOnly }],
    preparedPages: [],
    missingPages: ["KMG Hotels portfolio page", "Selected Austin property page", "Property decision-maker page"],
    nextAction: "Ask Kristie which Austin hotel is most realistic for one local offer or event and who can approve it.",
    ask: "Which hotel is most likely to say yes to a focused local pilot, and who should we meet first?",
    sources: [],
  },
  {
    id: "dana",
    priority: "1",
    name: "Downtown Austin Neighborhood Association (DANA)",
    segment: "Civic / resident distribution",
    relationshipStrength: "Warm / trusted",
    pageStatus: "Ready",
    why: "DANA can provide resident trust, language review, event distribution, and one credible neighborhood channel.",
    pilot: "One approved resident update, one calendar or event-feed connection, and one measurable distribution path.",
    assets: ["DANA resident audience", "Newsletter / email", "Calendar and event feed", "Board, president, and vice-president routes"],
    assetNote: "Use approved DANA language and confirm the current distribution owner before launch.",
    contacts: [
      { name: "Current DANA President", role: "Civic approval and language route", status: "Prepared leadership page; current officeholder to confirm", channel: "Use the prepared DANA leadership page." },
      { name: "Current DANA Vice President", role: "Civic and operating route", status: "Prepared leadership page; current officeholder to confirm", channel: "Use the prepared DANA leadership page." },
      { name: "Current board / communications owner", role: "Distribution", status: "To identify", channel: researchOnly },
    ],
    preparedPages: ["DANA", "DANA board member", "DANA president", "DANA vice president", "Resident Mixer"],
    missingPages: ["Current distribution owner / approved launch language"],
    nextAction: "Confirm approved language, the simplest email or calendar distribution path, and the person who owns it.",
    ask: "Who should review the resident language and share the first useful downtown update?",
    sources: [],
  },
  {
    id: "downtown-austin-alliance",
    priority: "2",
    name: "Downtown Austin Alliance",
    segment: "Civic / business network",
    relationshipStrength: "Target",
    pageStatus: "Research required",
    why: "The Alliance can connect property, business, public-program, and communications relationships through a trusted downtown platform.",
    pilot: "Two property or business introductions, one public program, and one communications channel.",
    assets: ["Downtown property network", "Business network", "Public programs", "Research and communications channels"],
    assetNote: "Specific participating properties and programs must be named by the Alliance team.",
    contacts: [{ name: "Current Alliance property / business-network owner", role: "Civic and distribution route", status: "Research required", channel: researchOnly }],
    preparedPages: [],
    missingPages: ["Downtown Austin Alliance target page", "Current decision-maker / communications owner page"],
    nextAction: "Identify one current Alliance owner for property relationships and one communications route.",
    ask: "Who can introduce two relevant properties or businesses and one trusted distribution channel?",
    sources: [["Downtown Austin Alliance", "https://downtownaustin.com/"]],
  },
  {
    id: "waterloo-greenway",
    priority: "2",
    name: "Waterloo Greenway",
    segment: "Civic / culture / events",
    relationshipStrength: "Target",
    pageStatus: "Ready or existing workspace route",
    why: "Waterloo Greenway can provide useful event content, cultural credibility, and a resident-facing activation tied to public space.",
    pilot: "Event-feed partnership plus one measurable resident-facing activation at Waterloo Park.",
    assets: ["Waterloo Park", "Moody Amphitheater", "Greenway events", "Public art, trails, volunteer and community programs"],
    assetNote: "Confirm current event-feed permissions and the program owner for the selected activation.",
    contacts: [{ name: "Current programming / partnerships owner", role: "Event-feed and activation approver", status: "Research required", channel: researchOnly }],
    preparedPages: ["Waterloo Greenway workspace context"],
    missingPages: ["Current partnerships / programming owner page"],
    nextAction: "Confirm the event-feed route and one event or program suited to a 30-day resident activation.",
    ask: "Could we connect the Waterloo event feed and test one resident-facing activation with a clear report date?",
    sources: [],
  },
  {
    id: "do512",
    priority: "2",
    name: "Do512",
    segment: "Media / referral distribution",
    relationshipStrength: "Target",
    pageStatus: "Ready",
    why: "Do512 can provide timely event reach and a trackable referral path without requiring a broad media campaign.",
    pilot: "A co-branded This Week Downtown guide with one trackable referral route.",
    assets: ["Do512 audience", "This Week Downtown guide", "Event-discovery distribution"],
    assetNote: "Confirm current editorial, partnership, and measurement owners.",
    contacts: [{ name: "Current partnerships / editorial owner", role: "Media approval and distribution", status: "Research required", channel: researchOnly }],
    preparedPages: ["Do512"],
    missingPages: ["Current contact / campaign-owner page"],
    nextAction: "Identify the person who can approve a small co-branded guide and track the referral path.",
    ask: "Who is the right person for a simple This Week Downtown guide with trackable referrals?",
    sources: [],
  },
  {
    id: "visit-austin",
    priority: "2",
    name: "Visit Austin",
    segment: "Destination / visitor distribution",
    relationshipStrength: "Target",
    pageStatus: "Ready",
    why: "Visit Austin can connect a resident and visitor guide to trusted destination information and citywide reach.",
    pilot: "One measurable downtown resident and visitor experience guide.",
    assets: ["Visit Austin audience", "Destination guides", "Visitor information", "Downtown experience distribution"],
    assetNote: "Confirm the current partnership and editorial route before proposing a guide.",
    contacts: [{ name: "Current partnerships / content owner", role: "Guide approval and distribution", status: "Research required", channel: researchOnly }],
    preparedPages: ["Visit Austin"],
    missingPages: ["Current partnerships contact page"],
    nextAction: "Identify one current partnerships owner and a guide format that can be measured.",
    ask: "Could we pilot one useful, measurable Downtown Austin experience guide?",
    sources: [],
  },
  {
    id: "austin-way-modern-luxury",
    priority: "2",
    name: "Austin Way / Modern Luxury",
    segment: "Media / lifestyle referral",
    relationshipStrength: "Target",
    pageStatus: "Missing",
    why: "A premium local media relationship can frame the launch as a useful downtown story rather than a promotion.",
    pilot: "One concise launch story, guide, or referral feature with a measurable destination.",
    assets: ["Austin Way audience", "Modern Luxury network", "Lifestyle editorial and referral reach"],
    assetNote: "Confirm the current Austin editorial and commercial structure before outreach.",
    contacts: [{ name: "Current Austin editorial / partnerships lead", role: "Story or guide approval", status: "Research required", channel: researchOnly }],
    preparedPages: [],
    missingPages: ["Austin Way / Modern Luxury target page", "Current contact page"],
    nextAction: "Identify the current Austin decision-maker and choose one simple story or guide angle.",
    ask: "Who is the best person to discuss a useful Downtown Perks launch story or guide?",
    sources: [],
  },
  {
    id: "crexi",
    priority: "2",
    name: "Crexi",
    segment: "Commercial leasing intelligence / referral",
    relationshipStrength: "Warm",
    pageStatus: "Internal relationship route",
    why: "Crexi can surface early signals on new restaurant, retail, office, and ground-floor tenant activity.",
    pilot: "A recurring tenant-signal referral path focused on Frost Bank Tower, Rainey, and the downtown core.",
    assets: ["Commercial tenant signals", "Restaurant and retail listings", "Office and ground-floor activity", "Frost / Rainey / core opportunity watch"],
    assetNote: "Crexi provides signals and relationships, not approval for the properties or tenants surfaced.",
    contacts: [{ name: "Tamara Stuart", role: "Warm Crexi relationship", status: "Warm", channel: warmOnly }],
    preparedPages: [],
    missingPages: ["Crexi referral brief / current contact route"],
    nextAction: "Ask Tamara for early signals and the best route to relevant listing agents, owners, or tenants.",
    ask: "What new downtown tenants or ground-floor opportunities should we be watching now?",
    sources: [],
  },
  {
    id: "urbanspace",
    priority: "2",
    name: "Urbanspace",
    segment: "Real estate brokerage / downtown relationship",
    relationshipStrength: "Warm",
    pageStatus: "Internal relationship route",
    why: "Urbanspace can connect downtown condo, Rainey, ownership, and development relationships through one trusted contact.",
    pilot: "One owner or building introduction tied to Plaza on Republic Square, Rainey, or a downtown condo opportunity.",
    assets: ["Plaza on Republic Square relationship", "Rainey-area buildings", "Downtown condo relationships", "Owner and development network"],
    assetNote: "This is relationship reach, not an ownership or management claim.",
    contacts: [{ name: "Meg Alley", role: "Warm Urbanspace relationship", status: "Warm", channel: warmOnly }],
    preparedPages: [],
    missingPages: ["Plaza on Republic Square target page — confirm", "Selected owner / building page"],
    nextAction: "Ask Meg which building or owner is easiest to approach and whether Plaza on Republic Square should be its own target.",
    ask: "Which downtown building or owner is most likely to test a resident-first pilot now?",
    sources: [],
  },
  {
    id: "compass",
    priority: "2",
    name: "Compass",
    segment: "Luxury residential brokerage / referral",
    relationshipStrength: "Warm",
    pageStatus: "Internal relationship route",
    why: "Compass contacts can identify the condo buildings clients actually use and the decision-makers behind them.",
    pilot: "One warm building or management introduction based on current luxury-condo activity.",
    assets: ["Northshore relationship scope", "Four Seasons Residences relationship scope", "The Austonian relationship scope", "Spring Condominiums relationship scope", "Luxury buyer and resident network"],
    assetNote: "These are relationship targets, not Compass-owned or Compass-managed assets.",
    contacts: [
      { name: "Katie Daniel", role: "Warm Compass relationship", status: "Warm", channel: warmOnly },
      { name: "Nanette Labastida", role: "Warm Compass relationship", status: "Warm", channel: warmOnly },
    ],
    preparedPages: ["Northshore", "Four Seasons Residences", "The Austonian", "Spring Condominiums"],
    missingPages: ["Selected decision-maker / management intro page"],
    nextAction: "Ask Katie or Nanette which building their clients talk about most and who can authorize a first test.",
    ask: "Which downtown condo buildings are most relevant now, and who is the cleanest warm introduction?",
    sources: [],
  },
  {
    id: "moreland-properties",
    priority: "2",
    name: "Moreland Properties",
    segment: "Luxury residential brokerage / referral",
    relationshipStrength: "Warm",
    pageStatus: "Internal relationship route",
    why: "Moreland can open established Austin luxury condo, seller, developer, and long-term ownership relationships.",
    pilot: "One warm introduction tied to a high-value downtown residential building or developer.",
    assets: ["Northshore relationship scope", "Four Seasons Residences relationship scope", "The Austonian relationship scope", "Spring Condominiums relationship scope", "Luxury seller and developer network"],
    assetNote: "These are relationship targets, not Moreland-owned or managed assets.",
    contacts: [
      { name: "Elsa Decker", role: "Warm Moreland Properties relationship", status: "Warm", channel: warmOnly },
      { name: "Jan Moreland", role: "Warm Moreland Properties relationship", status: "Warm", channel: warmOnly },
    ],
    preparedPages: ["Northshore", "Four Seasons Residences", "The Austonian", "Spring Condominiums"],
    missingPages: ["Selected developer / building decision-maker page"],
    nextAction: "Ask for one introduction tied to Northshore, Four Seasons, The Austonian, Spring, or the strongest current developer route.",
    ask: "Which established downtown relationship is most likely to move a small resident pilot forward?",
    sources: [],
  },
  {
    id: "christies-international-real-estate",
    priority: "2",
    name: "Christie’s International Real Estate",
    segment: "Luxury residential brokerage / referral",
    relationshipStrength: "Warm",
    pageStatus: "Internal relationship route",
    why: "Christie’s contacts can open high-end condo, buyer, and developer relationships through trusted introductions.",
    pilot: "One warm introduction to a luxury condo decision-maker or developer with an occupied downtown asset.",
    assets: ["The Austonian relationship scope", "Four Seasons Residences relationship scope", "High-end downtown condo network", "Buyer and developer relationships"],
    assetNote: "These are relationship targets, not Christie’s-owned or managed assets.",
    contacts: [
      { name: "Brett Silverman", role: "Warm Christie’s relationship", status: "Warm", channel: warmOnly },
      { name: "Andrea Hamilton", role: "Warm Christie’s relationship", status: "Warm", channel: warmOnly },
    ],
    preparedPages: ["The Austonian", "Four Seasons Residences"],
    missingPages: ["Selected decision-maker / developer page"],
    nextAction: "Ask whether Brett or Andrea knows a current decision-maker tied to The Austonian, Four Seasons, or another top building.",
    ask: "Who is the strongest current building or developer introduction for a focused resident pilot?",
    sources: [],
  },
  {
    id: "bramlett-partners",
    priority: "2",
    name: "Bramlett Partners",
    segment: "Residential brokerage / referral",
    relationshipStrength: "Warm",
    pageStatus: "Internal relationship route",
    why: "Bramlett can create agent reach, resident referrals, and practical intelligence on which buildings are easiest to activate.",
    pilot: "One agent-led building or resident introduction with a clear decision-maker route.",
    assets: ["Austin agent network", "Resident referrals", "Downtown building intelligence", "Buyer and seller relationships"],
    assetNote: "The specific building target should be selected through Mike’s current network.",
    contacts: [{ name: "Mike Ward", role: "Warm Bramlett Partners relationship", status: "Warm", channel: warmOnly }],
    preparedPages: [],
    missingPages: ["Selected agent / building introduction page"],
    nextAction: "Ask Mike which agents or buildings are easiest for a first resident-focused test.",
    ask: "Which agent or building relationship is most likely to create a real first conversation?",
    sources: [],
  },
  {
    id: "lifestyle-brand-set",
    priority: "3",
    name: "Lifestyle Brand Prospect Set",
    segment: "Brand / experience sponsor",
    relationshipStrength: "Research required",
    pageStatus: "Pages to create if pursued",
    why: "One useful local event or offer can prove brand participation through resident action rather than logo visibility.",
    pilot: "One brand, one real resident use case, one building or partner distribution channel, and one measurable response.",
    assets: ["YETI", "Tecovas", "lululemon", "Rivian"],
    assetNote: "This is a prospect set. No participation, access, or sponsorship is implied.",
    contacts: [{ name: "Current local partnerships / community owner", role: "Brand activation approver", status: "Research required", channel: researchOnly }],
    preparedPages: [],
    missingPages: ["Selected brand partner page", "Local partnerships contact page"],
    nextAction: "Choose one brand with a credible resident use case and identify the local partnerships owner.",
    ask: "Would one useful downtown resident event or offer fit your current community priorities?",
    sources: [],
  },
  {
    id: "hotel-expansion-set",
    priority: "3",
    name: "Hotel Expansion Set",
    segment: "Hotel prospects",
    relationshipStrength: "Research required",
    pageStatus: "Pages to create if pursued",
    why: "These hotels provide follow-on options after the first hotel proof point is established.",
    pilot: "One hotel at a time: one local guide or offer, one event or dining feature, and one property owner.",
    assets: ["1 Hotel Austin", "Austin Proper", "Thompson Austin", "tommie Austin", "The LINE Austin", "The Driskill", "Fairmont Austin", "Hyatt Centric Congress Avenue Austin"],
    assetNote: "This is an expansion prospect set. Current ownership, management, operating status, and contact routes must be researched separately.",
    contacts: [{ name: "Current GM / marketing / sales / F&B lead", role: "Property approval and execution", status: "Research required", channel: researchOnly }],
    preparedPages: [],
    missingPages: ["Individual hotel partner pages", "Current property leadership pages"],
    nextAction: "Do not pursue until Hotel Van Zandt or White Lodging creates a useful proof point; then select the best-fit next hotel.",
    ask: "Which property has the strongest local-audience opportunity and cleanest operating path?",
    sources: [],
  },
];

export const collectionBuildingDirectory = [
  { property: "The Austonian", operator: "FirstService Residential — supplied", contact: "Shawn Bell — GM", email: "shawn.bell@fsresidential.com", phone: "512-827-2710", pageStatus: "Ready", route: "Direct building decision-maker route; reconfirm title and approval authority." },
  { property: "Four Seasons Residences", operator: "Four Seasons Residences", contact: "Sasha Horner Johnson", email: "Sasha.Horner@fourseasons.com", phone: "512-685-7777", pageStatus: "Ready", route: "Direct residence route; reconfirm title and communications authority." },
  { property: "Residences at 6G", operator: "Kairoi — supplied", contact: "Holly Garcia", email: "hgarcia@kairoi.com", phone: "512-212-9001", pageStatus: "Contact ready; page to confirm", route: "Direct property route; confirm current role and occupancy." },
  { property: "5 Fifty Five", operator: "Somerset Associations — supplied", contact: "Jim Reist", email: "jreist@somersetassociations.com", phone: "737-241-1051", pageStatus: "Contact ready; page to confirm", route: "Direct property / association route; confirm current authority." },
  { property: "Brown Building", operator: "FirstService Residential — supplied", contact: "Alana Ulrich", email: "maluhia.ulrich@fsresidential.com", phone: "512-620-7096", pageStatus: "Contact ready; page to confirm", route: "Direct property route; confirm current role and board / communications path." },
  { property: "Plaza Lofts", operator: "Somerset Associations — supplied", contact: "Amy Wissler", email: "awissler@somersetassociations.com", phone: "512-480-0448", pageStatus: "Contact ready; page to confirm", route: "Direct property / association route; confirm current authority." },
  { property: "Paseo", operator: "LV Collective + Greystar", contact: "Paseo Leasing / supplied onsite routes", email: "leasing@paseoatx.com", phone: "512-856-5117", pageStatus: "Ready", route: "Joint ownership / management pilot; confirm signer, legal, communications, and onsite owner." },
  { property: "Northshore", operator: "Current property management to confirm", contact: "Warm brokerage route via Compass / Moreland", email: "", phone: "", pageStatus: "Ready", route: "Use a warm introduction to identify the current approver and resident communications owner." },
  { property: "Spring Condominiums", operator: "Current association / management to confirm", contact: "Warm brokerage route via Compass / Moreland", email: "", phone: "", pageStatus: "Ready", route: "Use a warm introduction to identify the current approver and board path." },
  { property: "SkyHouse Austin", operator: "Current operator to confirm", contact: "Research required", email: "", phone: "", pageStatus: "Ready", route: "Verify current property management and communications authority." },
  { property: "Camden Rainey Street", operator: "Current Camden route to confirm", contact: "Research required", email: "", phone: "", pageStatus: "Ready", route: "Verify current property manager and regional decision-maker." },
  { property: "ROOST Rainey", operator: "Current operator to confirm", contact: "Research required", email: "", phone: "", pageStatus: "Ready", route: "Verify current operations and resident distribution path." },
  { property: "70 Rainey", operator: "Worth Ross route — current management to confirm", contact: "SaraMarie Blunt / Jack Thuet / Rikki Conner warm path", email: "info4hoa@worthross.com", phone: "855-435-4596", pageStatus: "Ready", route: "Confirm current portfolio status, community manager, and board approval path." },
  { property: "44 East", operator: "Worth Ross route — current management to confirm", contact: "SaraMarie Blunt / Jack Thuet / Rikki Conner warm path", email: "info4hoa@worthross.com", phone: "855-435-4596", pageStatus: "Pilot candidate", route: "Confirm current portfolio status, community manager, and board approval path." },
  { property: "900 S. 1st", operator: "Worth Ross route — current management to confirm", contact: "SaraMarie Blunt / Jack Thuet / Rikki Conner warm path", email: "info4hoa@worthross.com", phone: "855-435-4596", pageStatus: "Pilot candidate", route: "Confirm current portfolio status, community manager, and board approval path." },
  { property: "The Shore", operator: "Board / manager approval route", contact: "Current board or manager to identify", email: "", phone: "", pageStatus: "Ready", route: "One communication, one staff owner, and a measured 30-day pilot." },
  { property: "Plaza on Republic Square", operator: "Current owner / management to confirm", contact: "Meg Alley / Urbanspace warm route", email: "", phone: "", pageStatus: "Confirm dedicated page", route: "Confirm whether this should be a standalone property target and identify the current approver." },
];
