export const CTA_FLOW_DEFINITIONS = {
  start_here: {
    title: "Start here",
    description: "Tell us what you are trying to launch and we will route you into the right Downtown Perks path.",
    submitLabel: "Start this flow",
    successTitle: "Your kickoff request is in.",
    successBody: "We captured the role, source, and context. Next step is the right launch path for your use case.",
    fields: [
      { name: "partnerType", label: "Partner type", type: "select", options: ["properties", "hospitality", "venues", "brands", "civic", "resident", "other"], required: true },
      { name: "organization", label: "Organization or building", type: "text", required: true },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "goal", label: "Main goal", type: "textarea" },
    ],
  },
  pilot_request: {
    title: "Start a free pilot",
    description: "Open a pilot request with the right partner context already attached.",
    submitLabel: "Request pilot",
    successTitle: "Pilot request submitted.",
    successBody: "We captured the pilot context and next-step fit information.",
    fields: [
      { name: "partnerType", label: "Partner type", type: "select", options: ["properties", "hospitality", "venues", "brands", "civic"], required: true },
      { name: "organization", label: "Property, venue, hotel, or organization", type: "text", required: true },
      { name: "district", label: "District or downtown area", type: "text" },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "launchTimeframe", label: "Launch timeframe", type: "select", options: ["Immediately", "Within 30 days", "This quarter", "Exploring only"] },
    ],
  },
  availability_check: {
    title: "Check availability",
    description: "We will use the current route and district context to route this to the right partner team.",
    submitLabel: "Check availability",
    successTitle: "Availability check sent.",
    successBody: "We saved the role, district, and source context for follow-up.",
    fields: [
      { name: "partnerType", label: "Partner type", type: "select", options: ["properties", "hospitality", "venues", "brands", "civic", "resident"], required: true },
      { name: "organization", label: "Organization, building, or venue", type: "text" },
      { name: "district", label: "District", type: "text" },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
    ],
  },
  residential_onboarding: {
    title: "Connect your property",
    description: "Property onboarding flow with building and rollout context already attached.",
    submitLabel: "Submit property onboarding",
    successTitle: "Property request submitted.",
    successBody: "Next step is a property launch path tied to the building and district you submitted.",
    fields: [
      { name: "propertyName", label: "Property name", type: "text", required: true },
      { name: "address", label: "Address", type: "text", required: true },
      { name: "propertyType", label: "Property type", type: "select", options: ["Tower", "Condo", "Mid-rise", "Loft", "Mixed-use"], required: true },
      { name: "units", label: "Number of units", type: "number" },
      { name: "managementCompany", label: "Management company", type: "text" },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "role", label: "Role", type: "text" },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "launchTimeframe", label: "Launch timeframe", type: "select", options: ["Within 30 days", "This quarter", "This year"] },
    ],
  },
  hospitality_onboarding: {
    title: "Use this for guests",
    description: "Hotel onboarding with guest-flow context, QR entry points, and district awareness.",
    submitLabel: "Submit hospitality onboarding",
    successTitle: "Hospitality request submitted.",
    successBody: "Next step is a guest-entry and local recommendation setup path.",
    fields: [
      { name: "hotelName", label: "Hotel name", type: "text", required: true },
      { name: "address", label: "Address", type: "text", required: true },
      { name: "rooms", label: "Number of rooms", type: "number" },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "role", label: "Role", type: "text" },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "goal", label: "Guest experience goal", type: "textarea" },
    ],
  },
  venue_onboarding: {
    title: "Add your venue",
    description: "Venue onboarding with offer and event intent attached to the submission.",
    submitLabel: "Submit venue onboarding",
    successTitle: "Venue request submitted.",
    successBody: "We saved your venue context and launch intent for the next step.",
    fields: [
      { name: "venueName", label: "Venue name", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "address", label: "Address", type: "text", required: true },
      { name: "website", label: "Website or Instagram", type: "text" },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "intent", label: "What do you want to launch?", type: "select", options: ["Perks", "Events", "Both"], required: true },
    ],
  },
  brand_campaign: {
    title: "Launch campaign",
    description: "Brand campaign request with district, placement, and activation context.",
    submitLabel: "Submit campaign brief",
    successTitle: "Campaign brief submitted.",
    successBody: "Next step is district, placement, and activation fit review.",
    fields: [
      { name: "brandName", label: "Brand or organization", type: "text", required: true },
      { name: "campaignName", label: "Campaign name", type: "text", required: true },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "districts", label: "Desired districts", type: "text" },
      { name: "objective", label: "Campaign objective", type: "textarea", required: true },
      { name: "activationType", label: "Activation type", type: "text" },
    ],
  },
  civic_onboarding: {
    title: "Become a civic partner",
    description: "Civic initiative request with district, event, and participation context attached.",
    submitLabel: "Submit civic request",
    successTitle: "Civic request submitted.",
    successBody: "Next step is district-layer and participation-tracking review.",
    fields: [
      { name: "organization", label: "Organization name", type: "text", required: true },
      { name: "initiative", label: "Initiative or district", type: "text", required: true },
      { name: "name", label: "Contact name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "goal", label: "Public objective", type: "textarea", required: true },
    ],
  },
  resident_card: {
    title: "Get your perks card",
    description: "Resident card request with building and source context attached.",
    submitLabel: "Request my card",
    successTitle: "Card request saved.",
    successBody: "We captured your building and contact context for the next step.",
    fields: [
      { name: "name", label: "Your name", type: "text", required: true },
      { name: "phone", label: "Phone", type: "tel", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "building", label: "Building", type: "text", required: true },
    ],
  },
  support_request: {
    title: "Support request",
    description: "This keeps the current page and selected item context attached to the support request.",
    submitLabel: "Send support request",
    successTitle: "Support request sent.",
    successBody: "We saved the current route, role, and item context with your request.",
    fields: [
      { name: "name", label: "Name", type: "text" },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "issueType", label: "Issue type", type: "select", options: ["General", "Resident access", "Partner onboarding", "Map issue", "Perk or event issue"], required: true },
      { name: "message", label: "What happened?", type: "textarea", required: true },
    ],
  },
};

export function getDefaultFlowValues(type, context = {}) {
  const partnerType =
    context.partnerType ||
    context.initialValues?.partnerType ||
    context.pageContext?.partnerType ||
    "";

  return {
    partnerType,
    organization: context.organization || context.pageContext?.organization || "",
    district: context.district || context.pageContext?.district || "",
    name: context.user?.full_name || context.initialValues?.name || "",
    email: context.user?.email || context.initialValues?.email || "",
    phone: context.user?.phone || context.initialValues?.phone || "",
    building: context.pageContext?.building || "",
    address: context.pageContext?.address || "",
    goal: context.initialValues?.goal || "",
    launchTimeframe: context.initialValues?.launchTimeframe || "",
    venueName: context.pageContext?.venueName || context.entity?.name || "",
    hotelName: context.pageContext?.hotelName || context.entity?.name || "",
    propertyName: context.pageContext?.propertyName || context.entity?.name || "",
    brandName: context.pageContext?.brandName || "",
    campaignName: context.pageContext?.campaignName || "",
    initiative: context.pageContext?.initiative || "",
    objective: context.pageContext?.objective || "",
    activationType: context.pageContext?.activationType || "",
    intent: context.pageContext?.intent || "",
    ...context.initialValues,
  };
}
