export const perkImageRegistry: Record<string, string> = {
  "the-bowie": "/images/map-entities/properties/BOWIE.jpeg",
  bowie: "/images/map-entities/properties/BOWIE.jpeg",
  "amli-downtown": "/images/map-entities/properties/amli-downtown.jpeg",
  amli: "/images/map-entities/properties/amli-downtown.jpeg",
  "amli-south-shore": "/images/map-entities/properties/amli-building.jpeg",
  "the-independent": "/images/map-entities/properties/INDEPENDANT INFINITY POOL.jpeg",
  independent: "/images/map-entities/properties/INDEPENDANT INFINITY POOL.jpeg",
  "the-austonian": "/images/map-entities/perks/austonian_lobby_1779052725341.png",
  austonian: "/images/map-entities/perks/austonian_lobby_1779052725341.png",
  "w-austin": "/images/map-entities/perks/waustin_pool_1779052756806.png",
  "rivian": "/images/map-entities/brand-rivian/9JvnMPQ8kGuv11XCFhP4qI_0lIktNCTBBolhYsLAFdFrKtTRzkUq5Q31tv6T9ELH3voX6p5GdrTZtXeDJWPYBEvUKXwLboA0PHejrLBKAKZRKo7n0xwA5CQMUmC8eVeK__frO4QU1gVFAspV_WYn7zp3DhW7gT6T0Q9jZr3jl_veaPOYtJKM9M09OEVs68Sg.jpeg",
  "rivian-downtown-austin-activation": "/images/imported/perks/rivian-campaign.png",
  "yeti": "/images/map-entities/brand-yeti/yeti-flagship-interior.jpg",
  "yeti-flagship": "/images/map-entities/brand-yeti/yeti-flagship-interior.jpg",
  "yeti-congress-activation": "/images/map-entities/brand-yeti/yeti-austin-fc.png",
  "yeti-congress-district-activation": "/images/map-entities/brand-yeti/yeti-austin-fc.png",
  "kendra-scott": "/images/map-entities/brand-kendra-scott/kendra_scott_lifestyle_reference.png",
  "lululemon": "/images/imported/perks/lululemon-yoga-leggings-64529a1e874e4.webp",
  "topo-chico": "/images/map-entities/brand-topo-chico/topo-chico-bottle-yellow.jpeg",
  "heritage-boots": "/images/map-entities/brand-heritage-boots/made-in-texas-opener-Nevena-christi-el-paso.jpg",
  "tecovas": "/images/map-entities/brand-tecovas/Chilis_Tecovas_Booth_Boots_2.jpg",
  "banger-s": "/images/restaurants/bangers-bar.webp",
  "banger-s-sausage-house-and-beer-garden": "/images/restaurants/bangers-bar.webp",
  "banger-s-sausage-house-and-beer-garden-way-312335014": "/images/restaurants/bangers-bar.webp",
  "banger-s-sausage-house-beer-garden": "/images/restaurants/bangers-bar.webp",
  "banger-s-sausage-house-beer-garden-node-12485227010": "/images/restaurants/bangers-bar.webp",
  "partner-bangers": "/images/restaurants/bangers-bar.webp",
  "stay-put": "/images/imported/perks/stayput.png",
  "the-stay-put": "/images/imported/perks/stayput.png",
  "the-stay-put-way-1288159284": "/images/imported/perks/stayput.png",
  "partner-stay-put": "/images/imported/perks/stayput.png",
  "half-step": "/images/restaurants/half-step.jpg",
  "half-step-node-3181804699": "/images/restaurants/half-step.jpg",
  "partner-half-step": "/images/restaurants/half-step.jpg",
  "lustre-pearl": "/images/imported/perks/rainey-is-back.png",
  "lustre-pearl-way-379221708": "/images/imported/perks/rainey-is-back.png",
  "partner-lustre-pearl": "/images/imported/perks/rainey-is-back.png",
  "partner-lustre-pearl-rainey": "/images/imported/perks/rainey-is-back.png",
  "geraldine-s": "/images/imported/perks/geraldine-s.jpg",
  "geraldine-s-node-4633609354": "/images/imported/perks/geraldine-s.jpg",
  "partner-geraldines": "/images/imported/perks/geraldine-s.jpg",
  "partner-hotel-van-zandt": "/images/imported/perks/hotel-van-zandt-2560x1570.webp",
  "anthem": "/images/map-entities/rainey-bars/anthem.jpg",
  "anthem-node-7111035687": "/images/map-entities/rainey-bars/anthem.jpg",
  "emmer-rye": "/images/restaurants/emmer-rye-interior.jpg",
  "emmer-rye-node-8991620975": "/images/restaurants/emmer-rye-interior.jpg",
  "amaya": "/images/map-entities/rainey-bars/amaya.jpeg",
  "via-313": "/images/imported/perks/via313.jpg",
  "via-313-way-1350777573": "/images/imported/perks/via313.jpg",
  "via-313-pizza": "/images/imported/perks/via313.jpg",
  "via-313-pizza-node-11390573667": "/images/imported/perks/via313.jpg",
  "partner-via-313": "/images/imported/perks/via313.jpg",
  "moody-theater": "/images/map-entities/perks/moody_theater_live_music_1779052684229.png",
  "moody-ampitheater-at-waterloo-park": "/images/map-entities/perks/moody_theater_live_music_1779052684229.png",
  "waterloo-park": "/images/map-entities/perks/civic_lake_trail_1779052853070.png",
  "waterloo-greenway": "/images/map-entities/perks/civic_lake_trail_1779052853070.png",
  "republic-square": "/images/map-entities/perks/civic_republic_square_1779052838327.png",
};

export const categoryImageFallbacks: Record<string, string> = {
  property: "/images/reports/the-independent-austin-tower.jpg",
  residential: "/images/reports/the-independent-austin-tower.jpg",
  hotel: "/images/map-entities/perks/partner_hotel_rooftop_1779052803267.png",
  hospitality: "/images/map-entities/perks/partner_hotel_rooftop_1779052803267.png",
  event: "/images/map-entities/perks/neon_night_market_1779052637850.png",
  offer: "/images/map-entities/perks/partner_dining_patio_1779052819620.png",
  perk: "/images/map-entities/perks/partner_dining_patio_1779052819620.png",
  brand: "/images/map-entities/perks/commercial_street_level_1779052788888.png",
  civic: "/images/map-entities/perks/civic_republic_square_1779052838327.png",
  service: "/images/map-entities/perks/commercial_lobby_arrival_1779052774111.png",
  "bar-nightlife": "/images/map-entities/perks/neon_night_market_1779052637850.png",
  "restaurant-dining": "/images/map-entities/perks/partner_dining_patio_1779052819620.png",
  "coffee-cafe": "/images/map-entities/perks/partner_coffee_shop_1779052868356.png",
  "retail-business": "/images/map-entities/perks/commercial_street_level_1779052788888.png",
  "fitness-wellness": "/images/map-entities/perks/partner_wellness_1779052883675.png",
  "event-happy-hour": "/images/map-entities/perks/neon_night_market_1779052637850.png",
  "event-fitness": "/images/map-entities/perks/civic_lake_trail_1779052853070.png",
  "event-wellness": "/images/map-entities/perks/rooftop_yoga_1779052654323.png",
  "event-access": "/images/map-entities/perks/partner_hotel_rooftop_1779052803267.png",
  "brand-activation": "/images/map-entities/perks/commercial_street_level_1779052788888.png",
  "brand-real-estate": "/images/map-entities/properties/BOWIE.jpeg",
  "restoration-emergency-services": "/images/map-entities/perks/commercial_lobby_arrival_1779052774111.png",
  venue: "/images/map-entities/perks/partner_dining_patio_1779052819620.png",
  default: "/images/map-entities/perks/downtown_art_walk_1779052670656.png",
};

export const districtImageFallbacks: Record<string, string> = {
  seaholm: "/images/map-entities/perks/seaholm_coworking_1779052742037.png",
  rainey: "/images/map-entities/rainey-bars/rainey-street.jpeg",
  "west 6th": "/images/map-entities/perks/neon_night_market_1779052637850.png",
  congress: "/images/map-entities/perks/civic_republic_square_1779052838327.png",
  "red river": "/images/map-entities/perks/moody_theater_live_music_1779052684229.png",
  "lady bird lake": "/images/map-entities/perks/civic_lake_trail_1779052853070.png",
};
