const env = import.meta.env;

type StripeProductConfig = {
  productId: string;
  priceId: string;
  checkoutUrl: string;
};

function annualProduct(productKey: string, priceKey: string): StripeProductConfig {
  return {
    productId: env[`VITE_${productKey}`] || "",
    priceId: env[`VITE_${priceKey}`] || env[priceKey] || "",
    checkoutUrl: "",
  };
}

function product(productKey: string, priceKey: string, urlKey: string): StripeProductConfig {
  return {
    productId: env[`VITE_${productKey}`] || "",
    priceId: env[`VITE_${priceKey}`] || env[priceKey] || "",
    checkoutUrl: env[`VITE_${urlKey}`] || "",
  };
}

export const STRIPE_PRODUCTS = {
  venueFreeListing: { productId: "", priceId: "", checkoutUrl: "" },
  venueBasicAnnual: annualProduct("STRIPE_PRODUCT_VENUE_BASIC_ANNUAL", "STRIPE_PRICE_VENUE_BASIC_ANNUAL"),
  venueGrowthAnnual: annualProduct("STRIPE_PRODUCT_VENUE_GROWTH_ANNUAL", "STRIPE_PRICE_VENUE_GROWTH_ANNUAL"),
  venueProAnnual: annualProduct("STRIPE_PRODUCT_VENUE_PRO_ANNUAL", "STRIPE_PRICE_VENUE_PRO_ANNUAL"),
  propertyPartnerAnnual: annualProduct("STRIPE_PRODUCT_PROPERTY_PARTNER_ANNUAL", "STRIPE_PRICE_PROPERTY_PARTNER_ANNUAL"),
  propertyBasicBuildingAnnual: annualProduct("STRIPE_PRODUCT_PROPERTY_BASIC_BUILDING_ANNUAL", "STRIPE_PRICE_PROPERTY_BASIC_BUILDING_ANNUAL"),
  propertyResidentPlusAnnual: annualProduct("STRIPE_PRODUCT_PROPERTY_RESIDENT_PLUS_ANNUAL", "STRIPE_PRICE_PROPERTY_RESIDENT_PLUS_ANNUAL"),
  propertyProAnnual: annualProduct("STRIPE_PRODUCT_PROPERTY_PRO_ANNUAL", "STRIPE_PRICE_PROPERTY_PRO_ANNUAL"),
  hotelStarterAnnual: annualProduct("STRIPE_PRODUCT_HOTEL_STARTER_ANNUAL", "STRIPE_PRICE_HOTEL_STARTER_ANNUAL"),
  hotelProAnnual: annualProduct("STRIPE_PRODUCT_HOTEL_PRO_ANNUAL", "STRIPE_PRICE_HOTEL_PRO_ANNUAL"),
  brandAccessAnnual: annualProduct("STRIPE_PRODUCT_BRAND_ACCESS_ANNUAL", "STRIPE_PRICE_BRAND_ACCESS_ANNUAL"),
  brandCampaignsAnnual: annualProduct("STRIPE_PRODUCT_BRAND_CAMPAIGNS_ANNUAL", "STRIPE_PRICE_BRAND_CAMPAIGNS_ANNUAL"),
  civicBasicAnnual: annualProduct("STRIPE_PRODUCT_CIVIC_BASIC_ANNUAL", "STRIPE_PRICE_CIVIC_BASIC_ANNUAL"),
  civicPlusAnnual: annualProduct("STRIPE_PRODUCT_CIVIC_PLUS_ANNUAL", "STRIPE_PRICE_CIVIC_PLUS_ANNUAL"),
  civicProAnnual: annualProduct("STRIPE_PRODUCT_CIVIC_PRO_ANNUAL", "STRIPE_PRICE_CIVIC_PRO_ANNUAL"),
  realEstateAnnual: annualProduct("STRIPE_PRODUCT_PROPERTY_PARTNER_ANNUAL", "STRIPE_PRICE_PROPERTY_PARTNER_ANNUAL"),
  unlimitedPerkCampaignsAnnual: annualProduct("STRIPE_PRODUCT_UNLIMITED_PERK_CAMPAIGNS_ANNUAL", "STRIPE_PRICE_UNLIMITED_PERK_CAMPAIGNS_ANNUAL"),
  surveySeriesAnnual: annualProduct("STRIPE_PRODUCT_SURVEY_SERIES_ANNUAL", "STRIPE_PRICE_SURVEY_SERIES_ANNUAL"),
  analyticsPlusAnnual: annualProduct("STRIPE_PRODUCT_ANALYTICS_PLUS_ANNUAL", "STRIPE_PRICE_ANALYTICS_PLUS_ANNUAL"),
  analyticsProAnnual: annualProduct("STRIPE_PRODUCT_ANALYTICS_PRO_ANNUAL", "STRIPE_PRICE_ANALYTICS_PRO_ANNUAL"),
  districtSponsorAnnual: annualProduct("STRIPE_PRODUCT_DISTRICT_SPONSOR_ANNUAL", "STRIPE_PRICE_DISTRICT_SPONSOR_ANNUAL"),
  perkCampaign: product("STRIPE_PRODUCT_PERK_CAMPAIGN", "STRIPE_PRICE_PERK_CAMPAIGN", "STRIPE_CHECKOUT_PERK_CAMPAIGN"),
  featuredCampaign: product("STRIPE_PRODUCT_FEATURED_CAMPAIGN", "STRIPE_PRICE_FEATURED_CAMPAIGN", "STRIPE_CHECKOUT_FEATURED_CAMPAIGN"),
  sponsoredCampaign: product("STRIPE_PRODUCT_SPONSORED_CAMPAIGN", "STRIPE_PRICE_SPONSORED_CAMPAIGN", "STRIPE_CHECKOUT_SPONSORED_CAMPAIGN"),
  eventBoost: product("STRIPE_PRODUCT_EVENT_BOOST", "STRIPE_PRICE_EVENT_BOOST", "STRIPE_CHECKOUT_EVENT_BOOST"),
  featuredEvent: product("STRIPE_PRODUCT_FEATURED_EVENT", "STRIPE_PRICE_FEATURED_EVENT", "STRIPE_CHECKOUT_FEATURED_EVENT"),
  sponsoredEvent: product("STRIPE_PRODUCT_SPONSORED_EVENT", "STRIPE_PRICE_SPONSORED_EVENT", "STRIPE_CHECKOUT_SPONSORED_EVENT"),
  categoryFeatured7d: product("STRIPE_PRODUCT_CATEGORY_FEATURED_7D", "STRIPE_PRICE_CATEGORY_FEATURED_7D", "STRIPE_CHECKOUT_CATEGORY_FEATURED_7D"),
  categoryFeatured30d: product("STRIPE_PRODUCT_CATEGORY_FEATURED_30D", "STRIPE_PRICE_CATEGORY_FEATURED_30D", "STRIPE_CHECKOUT_CATEGORY_FEATURED_30D"),
  categoryFeatured90d: product("STRIPE_PRODUCT_CATEGORY_FEATURED_90D", "STRIPE_PRICE_CATEGORY_FEATURED_90D", "STRIPE_CHECKOUT_CATEGORY_FEATURED_90D"),
  districtFeatured30d: product("STRIPE_PRODUCT_DISTRICT_FEATURED_30D", "STRIPE_PRICE_DISTRICT_FEATURED_30D", "STRIPE_CHECKOUT_DISTRICT_FEATURED_30D"),
  districtFeatured90d: product("STRIPE_PRODUCT_DISTRICT_FEATURED_90D", "STRIPE_PRICE_DISTRICT_FEATURED_90D", "STRIPE_CHECKOUT_DISTRICT_FEATURED_90D"),
  nearbyBroadcast5Min: product("STRIPE_PRODUCT_NEARBY_BROADCAST_5_MIN", "STRIPE_PRICE_NEARBY_BROADCAST_5_MIN", "STRIPE_CHECKOUT_NEARBY_BROADCAST_5_MIN"),
  nearbyBroadcast10Min: product("STRIPE_PRODUCT_NEARBY_BROADCAST_10_MIN", "STRIPE_PRICE_NEARBY_BROADCAST_10_MIN", "STRIPE_CHECKOUT_NEARBY_BROADCAST_10_MIN"),
  nearbyBroadcastDistrict: product("STRIPE_PRODUCT_NEARBY_BROADCAST_DISTRICT", "STRIPE_PRICE_NEARBY_BROADCAST_DISTRICT", "STRIPE_CHECKOUT_NEARBY_BROADCAST_DISTRICT"),
  nearbyBroadcastDowntown: product("STRIPE_PRODUCT_NEARBY_BROADCAST_DOWNTOWN", "STRIPE_PRICE_NEARBY_BROADCAST_DOWNTOWN", "STRIPE_CHECKOUT_NEARBY_BROADCAST_DOWNTOWN"),
  smsBroadcast500: product("STRIPE_PRODUCT_SMS_BROADCAST_500", "STRIPE_PRICE_SMS_BROADCAST_500", "STRIPE_CHECKOUT_SMS_BROADCAST_500"),
  smsBroadcast2500: product("STRIPE_PRODUCT_SMS_BROADCAST_2500", "STRIPE_PRICE_SMS_BROADCAST_2500", "STRIPE_CHECKOUT_SMS_BROADCAST_2500"),
  smsBroadcast5000: product("STRIPE_PRODUCT_SMS_BROADCAST_5000", "STRIPE_PRICE_SMS_BROADCAST_5000", "STRIPE_CHECKOUT_SMS_BROADCAST_5000"),
  singleSurvey: product("STRIPE_PRODUCT_SINGLE_SURVEY", "STRIPE_PRICE_SINGLE_SURVEY", "STRIPE_CHECKOUT_SINGLE_SURVEY"),
  customResearchProject: product("STRIPE_PRODUCT_CUSTOM_RESEARCH_PROJECT", "STRIPE_PRICE_CUSTOM_RESEARCH_PROJECT", "STRIPE_CHECKOUT_CUSTOM_RESEARCH_PROJECT"),
  inVenueActivation: product("STRIPE_PRODUCT_IN_VENUE_ACTIVATION", "STRIPE_PRICE_IN_VENUE_ACTIVATION", "STRIPE_CHECKOUT_IN_VENUE_ACTIVATION"),
  propertyActivation: product("STRIPE_PRODUCT_PROPERTY_ACTIVATION", "STRIPE_PRICE_PROPERTY_ACTIVATION", "STRIPE_CHECKOUT_PROPERTY_ACTIVATION"),
  multiLocationActivation: product("STRIPE_PRODUCT_MULTI_LOCATION_ACTIVATION", "STRIPE_PRICE_MULTI_LOCATION_ACTIVATION", "STRIPE_CHECKOUT_MULTI_LOCATION_ACTIVATION"),
  streetTeamHalfDay: product("STRIPE_PRODUCT_STREET_TEAM_HALF_DAY", "STRIPE_PRICE_STREET_TEAM_HALF_DAY", "STRIPE_CHECKOUT_STREET_TEAM_HALF_DAY"),
  streetTeamFullDay: product("STRIPE_PRODUCT_STREET_TEAM_FULL_DAY", "STRIPE_PRICE_STREET_TEAM_FULL_DAY", "STRIPE_CHECKOUT_STREET_TEAM_FULL_DAY"),
  buildingPlacementPack: product("STRIPE_PRODUCT_BUILDING_PLACEMENT_PACK", "STRIPE_PRICE_BUILDING_PLACEMENT_PACK", "STRIPE_CHECKOUT_BUILDING_PLACEMENT_PACK"),
  campaignLaunchKit: product("STRIPE_PRODUCT_CAMPAIGN_LAUNCH_KIT", "STRIPE_PRICE_CAMPAIGN_LAUNCH_KIT", "STRIPE_CHECKOUT_CAMPAIGN_LAUNCH_KIT"),
  customPartnerReport: product("STRIPE_PRODUCT_CUSTOM_PARTNER_REPORT", "STRIPE_PRICE_CUSTOM_PARTNER_REPORT", "STRIPE_CHECKOUT_CUSTOM_PARTNER_REPORT"),
  surveyPulse: product("STRIPE_PRODUCT_SURVEY_PULSE", "STRIPE_PRICE_SURVEY_PULSE", "STRIPE_CHECKOUT_SURVEY_PULSE"),
  seasonalSponsor: product("STRIPE_PRODUCT_SEASONAL_SPONSOR", "STRIPE_PRICE_SEASONAL_SPONSOR", "STRIPE_CHECKOUT_SEASONAL_SPONSOR"),
  residentJoinBuildingNotMember: product("STRIPE_PRODUCT_RESIDENT_JOIN_BUILDING_NOT_MEMBER", "STRIPE_PRICE_RESIDENT_JOIN_BUILDING_NOT_MEMBER", "STRIPE_CHECKOUT_RESIDENT_JOIN_BUILDING_NOT_MEMBER"),
} as const;

export type StripeProductKey = keyof typeof STRIPE_PRODUCTS;
