import React from 'react'
import ReactDOM from 'react-dom/client'
import App from '@/App.jsx'
import '@/index.css'
import '@/styles/map-glass-final.css'
import '@/styles/dp-recovery-final.css'
import '@/styles/search-rollup-final.css'
import '@/styles/search-console-premium-final.css'
import '@/styles/hero-glass-restoration-final.css'
import '@/styles/downtown-command-center.css'
import '@/styles/partner-workspace-reports-polish.css'
import '@/styles/ask-map-component-polish.css'
import '@/styles/downtown-platform-page-polish.css'
import '@/styles/homepage-standardization-patch.css'
import '@/styles/pricing-clean.css'
import '@/styles/contact-clean.css'
import '@/styles/typography-governance.css'
import '@/styles/production-quality-v1.css'
import '@/styles/campaign-planning-final.css'
import '@/styles/about-editorial-final.css'
import '@/styles/partner-map-polish-final.css'
import '@/styles/resident-drawer-polish-final.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <App />
)
