import React from 'react'
import ReactDOM from 'react-dom/client'
import App from '@/App.jsx'
import '@/index.css'
import '@/styles/map-glass-final.css'
import '@/styles/dp-recovery-final.css'
import '@/styles/search-rollup-final.css'
import '@/styles/search-console-premium-final.css'
import '@/styles/hero-glass-restoration-final.css'
import '@/styles/downtown-command-center.css'
import '@/styles/partner-workspace-reports-polish.css'
import '@/styles/ask-map-component-polish.css'
import '@/styles/downtown-platform-page-polish.css'
import '@/styles/homepage-standardization-patch.css'
import '@/styles/pricing-clean.css'
import '@/styles/contact-clean.css'
import '@/styles/typography-governance.css'
import '@/styles/production-quality-v1.css'
import '@/styles/campaign-planning-final.css'
import '@/styles/about-editorial-final.css'
import '@/styles/partner-map-polish-final.css'
import '@/styles/resident-drawer-polish-final.css'
import '@/styles/search-command-console-glass-final.css'
import '@/styles/partner-activity-drawer-final.css'
import '@/styles/pricing-polish-final.css'
import '@/styles/map-drawer-containment-final.css'
import '@/styles/partner-register-refactor-final.css'
import '@/styles/search-intent-chip-expansion-final.css'
import '@/styles/search-intent-two-rail-restore.css'
import '@/styles/workspace-overview-operating-final.css'
import '@/styles/workspace-platform-alignment-final.css'
import '@/styles/campaign-platform-alignment-final.css'
import '@/styles/map-drawer-premium-regression-final.css'
import '@/styles/partner-access-formatting-final.css'
import '@/styles/partner-signup-cleanup-final.css'
import '@/styles/inkind-partner-drawer-final.css'
import '@/styles/search-intent-rail-alignment-final.css'
import '@/styles/resident-product-alignment-final.css'
import '@/styles/partner-native-mobile-final.css'
import '@/styles/resident-native-mobile-final.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <App />
)
